name = "prunt"
description = ""
version = "1.0.0"

authors = ["Liam Powell"]
maintainers = ["Liam Powell <liam@liampll.com>"]
maintainers-logins = ["liampwll"]
licenses = "MIT"
website = ""
tags = []

[build-switches]
# Configured in GPR file.
"*".optimization = []
"*".debug_info = []
"*".runtime_checks = []
"*".compile_checks = []
"*".contracts = []
"*".style_checks = []
"*".ada_version = []
"*".source_encoding = []

[[depends-on]]
gnat_native = "^15.2.1001"
# From here: https://github.com/Prunt3D/prunt_alire_index/tree/master

[[depends-on]]
gnatcoll = "^25.0.0"

[[actions]]
type = "pre-build"
command = ["gnatmake", "-gnatW8", "-gnata", "-g", "prebuild.adb", "-o", "prebuild", "-bargs", "-Es"]

[[actions]]
type = "pre-build"
command = ["./prebuild"]
# TODO: Make this work on Windows

[[depends-on]]
simple_components = "^4.68.0"

[[depends-on]]
utilada = "^2.8.0"

[[depends-on]]
utilada_curl = "^2.8.0"

[[pins]]
simple_components = { url = "https://github.com/Prunt3D/dak_simple_components.git" }

[configuration.variables]
Enable_Test_Mocks = {type = "Boolean", default = false}

[[depends-on]]
vss_text = "^26.0.0"

[[depends-on]]
vss_extra = "^26.0.0"
