name = "prunt"
description = ""
version = "0.1.0-dev"

authors = ["Liam Powell"]
maintainers = ["Liam Powell <liam@liampll.com>"]
maintainers-logins = ["liampwll"]
licenses = "GPL-3.0-or-later"
website = ""
tags = []

[build-switches]
release.optimization = ["-O3", "-gnatn", "-fdata-sections", "-ffunction-sections", "-flto=auto", "-fuse-linker-plugin", "-ffat-lto-objects"]
development.contracts = "Yes"

[[depends-on]]
gnat_native = "^14.2.1"

[[depends-on]]
gnatcoll = "^24.0.0"

[[depends-on]]
ews = "^1.11.0"

[[pins]]
ews = { url = "https://github.com/Prunt3D/ews.git" }

[[actions]]
type = "pre-build"
command = ["ews_generator", "--input-dir", "html", "--output-dir", "generated_src_ews"]
