name = "prunt"
description = ""
version = "0.1.0-dev"

authors = ["Liam Powell"]
maintainers = ["Liam Powell <liam@liampll.com>"]
maintainers-logins = ["liampwll"]
licenses = "GPL-3.0-or-later"
website = ""
tags = []

[build-switches]
release.optimization = ["-O3", "-gnatn", "-fdata-sections", "-ffunction-sections", "-flto=auto", "-fuse-linker-plugin", "-ffat-lto-objects"]
development.contracts = "Yes"

[[depends-on]]
gnat_native = "^14.2.1"

[[depends-on]]
gnatcoll = "^23.0.0"

[[actions]]
type = "pre-build"
command = ["sh", "-c", "[ \"$PRUNT_SKIP_PRE_BUILD\" = true ] || (cd html && npm install webpack-cli && npx webpack)"]

[[actions]]
type = "pre-build"
command = ["sh", "-c", "[ \"$PRUNT_SKIP_PRE_BUILD\" = true ] || are --lang=Ada -o ./generated_src_html --content-only --name-access --rule=./html/package.xml ./html/dist"]

[[depends-on]]
simple_components = "^4.68.0"

[[depends-on]]
are = "^1.5.1"

[[depends-on]]
utilada = "^2.8.0"

[[depends-on]]
utilada_curl = "^2.8.0"

[[pins]]
simple_components = { url = "https://github.com/Prunt3D/dak_simple_components.git" }
