-----------------------------------------------------------------------------
--                                                                         --
--                   Part of the Prunt Motion Controller                   --
--                                                                         --
--            Copyright (C) 2026 Liam Powell (liam@prunt3d.com)            --
--                                                                         --
--  This program is free software: you can redistribute it and/or modify   --
--  it under the terms of the GNU General Public License as published by   --
--  the Free Software Foundation, either version 3 of the License, or      --
--  (at your option) any later version.                                    --
--                                                                         --
--  This program is distributed in the hope that it will be useful,        --
--  but WITHOUT ANY WARRANTY; without even the implied warranty of         --
--  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          --
--  GNU General Public License for more details.                           --
--                                                                         --
--  You should have received a copy of the GNU General Public License      --
--  along with this program.  If not, see <http://www.gnu.org/licenses/>.  --
--                                                                         --
-----------------------------------------------------------------------------

--  If you're reading this file then there's a good chance that you're wondering why the `Config_Data_To_User_Config`
--  functions are generating some convoluted nonsense with explicit statements instead of a nice, easy to generate
--  expression like everything else. The reason is that GNAT is broken and will generate bogus visibility errors when
--  using an aggregate expression to generate an array: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=124282

with Ada.Directories;
with Ada.Strings;       use Ada.Strings;
with Ada.Strings.Fixed; use Ada.Strings.Fixed;
with Ada.Text_IO;       use Ada.Text_IO;
with GNAT.Source_Info;
with VSS.Characters.Latin;
with VSS.String_Vectors;
with VSS.Strings.Conversions;

package body Config_Generator is

   pragma Extensions_Allowed (On);

   Out_Dir : constant String := "generated_src_modules";

   procedure Write_File (Filename : String; Content : Virtual_String) is
      File : Ada.Text_IO.File_Type;
   begin
      Put_Line ("Writing file: " & Filename);
      Create (File, Out_File, Filename);
      Put (File, Conversions.To_UTF_8_String (Content));
      Close (File);
   end Write_File;

   procedure Generate_Gcode_Dispatch (Filename : String; Data : Module_Data) is
      Letters         : String_Vectors.Vector;
      Current_Map_Out : Virtual_String;

      procedure Emit (Text : Virtual_String; Location : String := GNAT.Source_Info.Source_Location) is
      begin
         Current_Map_Out.Append (Text);
         Current_Map_Out.Append (" --  " & Conversions.To_Virtual_String (Location));
         Current_Map_Out.Append (VSS.Characters.Latin.Line_Feed);
      end Emit;

   begin
      Emit ("pragma Style_Checks (Off);");
      Emit
        ("--  This file is automatically generated based on the contents of "
         & Conversions.To_Virtual_String (Filename));
      Emit ("--  Run config_codegen to regenerate this file.");
      Emit ("pragma Warnings (Off, ""no entities of * are referenced"");");
      Emit ("with Prunt.Gcode_Arguments;");
      Emit ("with VSS.Characters.Latin;");
      Emit ("pragma Warnings (On, ""no entities of * are referenced"");");
      Emit ("separate (" & Data.Name & ")");
      Emit
        ("procedure Gcode_Dispatch (This : in out Module_Instance; Args : in out Gcode_Arguments.Arguments; "
         & "Planner : Prunt.Module_Types.Planner_Interface'Class; "
         & "Command_Identifier : Prunt.Module_Types.Gcode_Command_Identifier) is");
      Emit ("pragma Unsuppress (All_Checks);");
      Emit ("use type Prunt.Gcode_Arguments.Argument_Kind;");
      Emit ("begin");
      Emit ("pragma Extensions_Allowed (On);");
      Emit ("case Command_Identifier.Argument is");

      for C in Data.Gcode_Commands.Iterate loop
         declare
            Key : constant Gcode_Key := Gcode_Command_Maps.Key (C);
         begin
            if not Letters.Contains (Key.Letter) then
               Letters.Append (Key.Letter);
            end if;
         end;
      end loop;

      for L of Letters loop
         Emit ("when '" & L & "' =>");
         Emit ("case Command_Identifier.Number is");

         declare
            Numbers : String_Vectors.Vector;
         begin
            for C in Data.Gcode_Commands.Iterate loop
               declare
                  Key     : constant Gcode_Key := Gcode_Command_Maps.Key (C);
                  Num_Str : constant Virtual_String := Conversions.To_Virtual_String (Trim (Key.Number'Image, Both));
               begin
                  if Key.Letter = L and then not Numbers.Contains (Num_Str) then
                     Numbers.Append (Num_Str);
                  end if;
               end;
            end loop;

            for N of Numbers loop
               Emit ("when " & N & " =>");

               declare
                  Variants : constant Config_Types.Gcode_Command_Vectors.Vector :=
                    Data.Gcode_Commands.Element
                      ((Letter => L, Number => Integer'Value (Conversions.To_UTF_8_String (N))));
               begin

                  declare
                     First_Var : Boolean := True;
                  begin
                     for Variant of Variants loop
                        declare
                           Conditions : Virtual_String;
                           First_Cond : Boolean := True;
                        begin
                           for Arg_C in Variant.Arguments.Iterate loop
                              declare
                                 Arg_Name : constant Virtual_String := Gcode_Argument_Maps.Key (Arg_C);
                                 Arg_Data : constant Gcode_Argument_Data := Gcode_Argument_Maps.Element (Arg_C);
                                 Checks   : Virtual_String;

                                 procedure Add_Check (K : Virtual_String) is
                                 begin
                                    if Checks /= "" then
                                       Checks.Append (" or else ");
                                    end if;
                                    Checks.Append ("Args.Kind ('" & Arg_Name & "') = " & K);
                                 end Add_Check;
                              begin
                                 if Arg_Name /= "This" and then Arg_Name /= "Planner" then
                                    if Arg_Data.Arg_Kinds (Config_Types.Integer_Kind) then
                                       Add_Check ("Gcode_Arguments.Integer_Kind");
                                    end if;
                                    if Arg_Data.Arg_Kinds (Config_Types.Float_Kind) then
                                       Add_Check ("Gcode_Arguments.Float_Kind");
                                    end if;
                                    if Arg_Data.Arg_Kinds (Config_Types.String_Kind) then
                                       Add_Check ("Gcode_Arguments.String_Kind");
                                    end if;
                                    if Arg_Data.Arg_Kinds (Config_Types.Not_Present_Kind) then
                                       Add_Check ("Gcode_Arguments.Non_Existent_Kind");
                                    end if;
                                    if Arg_Data.Arg_Kinds (Config_Types.No_Value_Kind) then
                                       Add_Check ("Gcode_Arguments.No_Value_Kind");
                                    end if;

                                    if Checks /= "" then
                                       if not First_Cond then
                                          Conditions.Append (" and then ");
                                       end if;
                                       Conditions.Append ("(" & Checks & ")");
                                       First_Cond := False;
                                    end if;
                                 end if;
                              end;
                           end loop;

                           if Conditions = "" then
                              Conditions := "True";
                           end if;

                           Emit (Virtual_String'(if First_Var then "" else "els") & "if " & Conditions & " then");

                           declare
                              Args_Call : Virtual_String;
                              First_Arg : Boolean := True;
                           begin
                              for Arg_C in
                                Variant.Arguments.Iterate
                                when Gcode_Argument_Maps.Key (Arg_C) /= "This"
                                and then Gcode_Argument_Maps.Key (Arg_C) /= "Planner"
                              loop
                                 declare
                                    Arg_Name     : constant Virtual_String := Gcode_Argument_Maps.Key (Arg_C);
                                    Arg_Data     : constant Gcode_Argument_Data := Gcode_Argument_Maps.Element (Arg_C);
                                    Type_Name_St : constant String := Conversions.To_UTF_8_String (Arg_Data.Type_Name);
                                    Val_Expr     : Virtual_String;
                                 begin
                                    if not First_Arg then
                                       Args_Call.Append (", ");
                                    end if;

                                    if Index (Type_Name_St, "Optional_Float") > 0 then
                                       Val_Expr :=
                                         "(if Args.Kind ('"
                                         & Arg_Name
                                         & "') /= Gcode_Arguments.Non_Existent_Kind then "
                                         & "(Present => True, Value => Args.Consume_Float ('"
                                         & Arg_Name
                                         & "')) else (Present => False))";
                                       if Arg_Data.Default /= "" then
                                          raise Constraint_Error
                                            with
                                              "Optional_Float can not have default ("
                                              & L'Image
                                              & N'Image
                                              & ": "
                                              & Variant'Image
                                              & ")";
                                       end if;
                                    elsif Index (Type_Name_St, "Optional_Integer") > 0 then
                                       Val_Expr :=
                                         "(if Args.Kind ('"
                                         & Arg_Name
                                         & "') /= Gcode_Arguments.Non_Existent_Kind then "
                                         & "(Present => True, Value => Args.Consume_Integer ('"
                                         & Arg_Name
                                         & "')) else (Present => False))";
                                       if Arg_Data.Default /= "" then
                                          raise Constraint_Error
                                            with
                                              "Optional_Integer can not have default ("
                                              & L'Image
                                              & N'Image
                                              & ": "
                                              & Variant'Image
                                              & ")";
                                       end if;
                                    elsif Index (Type_Name_St, "Optional_String") > 0 then
                                       Val_Expr :=
                                         "(if Args.Kind ('"
                                         & Arg_Name
                                         & "') /= Gcode_Arguments.Non_Existent_Kind then "
                                         & "(Present => True, Value => Args.Consume_String ('"
                                         & Arg_Name
                                         & "')) else (Present => False))";
                                       if Arg_Data.Default /= "" then
                                          raise Constraint_Error
                                            with
                                              "Optional_String can not have default ("
                                              & L'Image
                                              & N'Image
                                              & ": "
                                              & Variant'Image
                                              & ")";
                                       end if;
                                    elsif Index (Type_Name_St, "Optional_No_Value") > 0 then
                                       Val_Expr :=
                                         "(Present => Args.Kind ('" & Arg_Name & "') = Gcode_Arguments.No_Value_Kind)";
                                       if Arg_Data.Default /= "" then
                                          raise Constraint_Error
                                            with
                                              "Optional_No_Value can not have default ("
                                              & L'Image
                                              & N'Image
                                              & ": "
                                              & Variant'Image
                                              & ")";
                                       end if;
                                    elsif Index (Type_Name_St, "Dimensionless") > 0 then
                                       if Arg_Data.Default /= "" then
                                          Val_Expr :=
                                            "Args.Consume_Float_Or_Default ('"
                                            & Arg_Name
                                            & "', "
                                            & Arg_Data.Default
                                            & ")";
                                       else
                                          Val_Expr := "Args.Consume_Float ('" & Arg_Name & "')";
                                       end if;
                                    elsif Index (Type_Name_St, "Argument_Integer") > 0 then
                                       if Arg_Data.Default /= "" then
                                          Val_Expr :=
                                            "Args.Consume_Integer_Or_Default ('"
                                            & Arg_Name
                                            & "', "
                                            & Arg_Data.Default
                                            & ")";
                                       else
                                          Val_Expr := "Args.Consume_Integer ('" & Arg_Name & "')";
                                       end if;
                                    elsif Index (Type_Name_St, "String") > 0 then
                                       if Arg_Data.Default /= "" then
                                          Val_Expr :=
                                            "Args.Consume_String_Or_Default ('"
                                            & Arg_Name
                                            & "', "
                                            & Arg_Data.Default
                                            & ")";
                                       else
                                          Val_Expr := "Args.Consume_String ('" & Arg_Name & "')";
                                       end if;
                                    else
                                       raise Constraint_Error
                                         with
                                           "Unhandled argument type ("
                                           & L'Image
                                           & N'Image
                                           & ": "
                                           & Variant'Image
                                           & ")";
                                    end if;

                                    Args_Call.Append (Arg_Name & " => " & Val_Expr);
                                    First_Arg := False;
                                 end;
                              end loop;

                              if not First_Arg then
                                 Args_Call := ", " & Args_Call;
                              end if;

                              Emit
                                (Data.Name
                                 & "."
                                 & Variant.Name
                                 & " (This => This, Planner => Planner"
                                 & Args_Call
                                 & ");");
                           end;

                           First_Var := False;
                        end;
                     end loop;
                     Emit ("else");
                     Emit ("raise Constraint_Error with ""No matching G-code variant found."";");
                     Emit ("end if;");
                  end;
               end;
            end loop;

            Emit ("when others =>");
            Emit ("raise Constraint_Error with ""Unknown G-code command."";");
         end;
         Emit ("end case;");
      end loop;

      Emit ("when others =>");
      Emit ("raise Constraint_Error with ""Unknown G-code command identifier."";");
      Emit ("end case;");
      Emit ("end Gcode_Dispatch;");

      Write_File
        (Ada.Directories.Compose
           (Containing_Directory => Out_Dir, Name => Ada.Directories.Base_Name (Filename) & "-gcode_dispatch.adb"),
         Current_Map_Out);
   end Generate_Gcode_Dispatch;

   procedure Generate_Gcode_Commands_List (Filename : String; Data : Module_Data) is
      Current_Map_Out : Virtual_String;

      procedure Emit (Text : Virtual_String; Location : String := GNAT.Source_Info.Source_Location) is
      begin
         Current_Map_Out.Append (Text);
         Current_Map_Out.Append (" --  " & Conversions.To_Virtual_String (Location));
         Current_Map_Out.Append (VSS.Characters.Latin.Line_Feed);
      end Emit;
   begin
      Emit ("pragma Style_Checks (Off);");
      Emit
        ("--  This file is automatically generated based on the contents of "
         & Conversions.To_Virtual_String (Filename));
      Emit ("--  Run config_codegen to regenerate this file.");
      Emit ("pragma Warnings (Off, ""no entities of * are referenced"");");
      Emit ("with Prunt.Gcode_Arguments;");
      Emit ("with VSS.Characters.Latin;");
      Emit ("pragma Warnings (On, ""no entities of * are referenced"");");
      Emit ("separate (" & Data.Name & ")");
      Emit ("function Gcode_Commands (This : Module) return Prunt.Module_Types.Gcode_Command_Vectors.Vector is");
      Emit ("pragma Unsuppress (All_Checks);");
      Emit ("begin");
      Emit ("return");
      Emit ("[");

      declare
         First_Cmd : Boolean := True;
      begin
         for C in Data.Gcode_Commands.Iterate loop
            declare
               Key : constant Gcode_Key := Gcode_Command_Maps.Key (C);
            begin
               for Info_Idx in Gcode_Command_Maps.Element (C).First_Index .. Gcode_Command_Maps.Element (C).Last_Index
               loop
                  declare
                     Info : constant Gcode_Command_Data := Gcode_Command_Maps.Element (C) (Info_Idx);
                  begin
                     if not First_Cmd then
                        Emit (",");
                     end if;
                     Emit
                       ("(Identifier  => ('"
                        & Key.Letter
                        & "', "
                        & Conversions.To_Virtual_String (Trim (Key.Number'Image, Both))
                        & "),");
                     Emit (" Name        => """ & Info.Name & """,");
                     Emit (" Description => """ & Info.Description & """,");
                     Emit (" Arguments   =>");

                     if Info.Arguments.Is_Empty then
                        Emit ("[])");
                     else
                        Emit ("[");
                        declare
                           First_Arg : Boolean := True;
                        begin
                           for Arg_C in Info.Arguments.Iterate loop
                              declare
                                 Arg_Name : constant Virtual_String := Gcode_Argument_Maps.Key (Arg_C);
                                 Arg_Data : constant Gcode_Argument_Data := Gcode_Argument_Maps.Element (Arg_C);
                                 Kinds    : Virtual_String;

                                 procedure Add_K (K : Virtual_String) is
                                 begin
                                    if Kinds /= "" then
                                       Kinds.Append (", ");
                                    end if;
                                    Kinds.Append (K & " => True");
                                 end Add_K;
                              begin
                                 if Arg_Name /= "This" and then Arg_Name /= "Planner" then
                                    if not First_Arg then
                                       Emit (",");
                                    end if;

                                    for Kind in Config_Types.Gcode_Argument_Kind loop
                                       if Arg_Data.Arg_Kinds (Kind) then
                                          case Kind is
                                             when Config_Types.Integer_Kind     =>
                                                Add_K ("Gcode_Arguments.Integer_Kind");

                                             when Config_Types.Float_Kind       =>
                                                Add_K ("Gcode_Arguments.Float_Kind");

                                             when Config_Types.String_Kind      =>
                                                Add_K ("Gcode_Arguments.String_Kind");

                                             when Config_Types.No_Value_Kind    =>
                                                Add_K ("Gcode_Arguments.No_Value_Kind");

                                             when Config_Types.Not_Present_Kind =>
                                                Add_K ("Gcode_Arguments.Non_Existent_Kind");
                                          end case;
                                       end if;
                                    end loop;

                                    if Kinds /= "" then
                                       Kinds.Append (", ");
                                    end if;
                                    Kinds.Append ("others => False");

                                    Emit
                                      ("'"
                                       & Arg_Name
                                       & "' => (Allowed_Kinds => ["
                                       & Kinds
                                       & "], Description => """
                                       & Arg_Data.Description
                                       & """)");
                                    First_Arg := False;
                                 end if;
                              end;
                           end loop;
                        end;
                        Emit ("])");
                     end if;

                     First_Cmd := False;
                  end;
               end loop;
            end;
         end loop;
      end;

      Emit ("];");
      Emit ("end Gcode_Commands;");

      Write_File
        (Ada.Directories.Compose
           (Containing_Directory => Out_Dir, Name => Ada.Directories.Base_Name (Filename) & "-gcode_commands.adb"),
         Current_Map_Out);
   end Generate_Gcode_Commands_List;

   procedure Generate_Files (Filename : String; Data : Module_Data; Global_Config : Config_Maps.Map) is
      Config_Map_Out, Reader_Out, Setter_Out : Virtual_String := "";

      Index_Level : Natural := 0;

      procedure Emit_Config_Map (Text : Virtual_String; Location : String := GNAT.Source_Info.Source_Location) is
      begin
         Config_Map_Out.Append (Text);
         Config_Map_Out.Append (" --  " & Conversions.To_Virtual_String (Location));
         Config_Map_Out.Append (VSS.Characters.Latin.Line_Feed);
      end Emit_Config_Map;

      procedure Emit_Reader (Text : Virtual_String; Location : String := GNAT.Source_Info.Source_Location) is
      begin
         Reader_Out.Append (Text);
         Reader_Out.Append (" --  " & Conversions.To_Virtual_String (Location));
         Reader_Out.Append (VSS.Characters.Latin.Line_Feed);
      end Emit_Reader;

      procedure Emit_Setter (Text : Virtual_String; Location : String := GNAT.Source_Info.Source_Location) is
      begin
         Setter_Out.Append (Text);
         Setter_Out.Append (" --  " & Conversions.To_Virtual_String (Location));
         Setter_Out.Append (VSS.Characters.Latin.Line_Feed);
      end Emit_Setter;

      function Path_To_Vector_Access_String (Path : String_Vectors.Vector) return Virtual_String is
         Result : Virtual_String := "";
      begin
         for I in Path.First_Index .. Path.Last_Index loop
            if I > Path.First_Index then
               Result := Result & ", ";
            end if;
            Result := Result & """" & Path (I) & """";
         end loop;

         return Result;
      end Path_To_Vector_Access_String;

      procedure Handle_Item
        (Item          : Config_Type;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Prefix    : Virtual_String);

      procedure Handle_Boolean
        (Boolean_Val   : Boolean_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Expr      : Virtual_String)
      is
         pragma Unreferenced (Boolean_Val);
         Path_Str : constant Virtual_String := Path_To_Vector_Access_String (Path);
      begin
         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_Boolean'(Description => """
            & Outer.Description
            & """, Default => "
            & Outer.Default
            & ")");
         Emit_Reader
           (Reader_Prefix
            & " := Boolean'(Data.Get(Prunt.Config.Config_Data_Paths.Vector'["
            & Path_Str
            & "]));");
         Emit_Setter ("Data.Set (Prunt.Config.Config_Data_Paths.Vector'[" & Path_Str & "], " & Ada_Expr & ");");
      end Handle_Boolean;

      procedure Handle_Float
        (Float_Val     : Float_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Expr      : Virtual_String)
      is
         Path_Str : constant Virtual_String := Path_To_Vector_Access_String (Path);
      begin
         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_Float'(Description => """
            & Outer.Description
            & """, Default => ("
            & Outer.Default
            & ")"
            & Virtual_String'(if Float_Val.Unit /= "" then " / (" & Float_Val.Unit & ")" else "")
            & ", Min => ("
            & Outer.Min
            & ")"
            & Virtual_String'(if Float_Val.Unit /= "" then " / (" & Float_Val.Unit & ")" else "")
            & ", Max => ("
            & Outer.Max
            & ")"
            & Virtual_String'(if Float_Val.Unit /= "" then " / (" & Float_Val.Unit & ")" else "")
            & ", Unit => """
            & (if Float_Val.Unit /= "" then Float_Val.Unit else Outer.Unit)
            & """)");
         Emit_Reader
           (Reader_Prefix
            & " := Data.Get(Prunt.Config.Config_Data_Paths.Vector'["
            & Path_Str
            & "])"
            & (if Float_Val.Unit /= "" then " * (" & Float_Val.Unit & ")" else "")
            & ";");
         Emit_Setter
           ("Data.Set (Prunt.Config.Config_Data_Paths.Vector'["
            & Path_Str
            & "], ("
            & Ada_Expr
            & ")"
            & (if Float_Val.Unit /= "" then " / (" & Float_Val.Unit & ")" else "")
            & ");");
      end Handle_Float;

      procedure Handle_Ratio
        (Ratio_Val     : Ratio_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Expr      : Virtual_String)
      is
         pragma Unreferenced (Ratio_Val);
         Path_Str : constant Virtual_String := Path_To_Vector_Access_String (Path);
      begin
         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_Float_Ratio'(Description => """
            & Outer.Description
            & """, Default => "
            & Outer.Default
            & ", Min => "
            & Outer.Min
            & ", Max => "
            & Outer.Max
            & ")");
         Emit_Reader (Reader_Prefix & " := Data.Get (Prunt.Config.Config_Data_Paths.Vector'[" & Path_Str & "]);");
         Emit_Setter ("Data.Set (Prunt.Config.Config_Data_Paths.Vector'[" & Path_Str & "], " & Ada_Expr & ");");
      end Handle_Ratio;

      procedure Handle_Integer
        (Integer_Val   : Integer_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Expr      : Virtual_String)
      is
         Path_Str : constant Virtual_String := Path_To_Vector_Access_String (Path);
      begin
         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_Integer'(Description => """
            & Outer.Description
            & """, Default => "
            & Outer.Default
            & Virtual_String'(if Integer_Val.Unit /= "" then " / " else "")
            & Integer_Val.Unit
            & ", Min => "
            & Outer.Min
            & (if Integer_Val.Unit = "" then "" else " / " & Integer_Val.Unit)
            & ", Max => "
            & Outer.Max
            & (if Integer_Val.Unit = "" then "" else " / " & Integer_Val.Unit)
            & ", Unit => """
            & (if Integer_Val.Unit /= "" then Integer_Val.Unit else Outer.Unit)
            & """)");
         Emit_Reader
           (Reader_Prefix
            & " := "
            & Outer.Type_Name
            & "(Long_Long_Integer'(Data.Get (Prunt.Config.Config_Data_Paths.Vector'["
            & Path_Str
            & "])));");
         Emit_Setter
           ("Data.Set (Prunt.Config.Config_Data_Paths.Vector'["
            & Path_Str
            & "], Long_Long_Integer ("
            & Ada_Expr
            & (if Integer_Val.Unit /= "" then " / " & Integer_Val.Unit else "")
            & "));");
      end Handle_Integer;

      procedure Handle_Component
        (Field         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Expr      : Virtual_String) is
      begin
         Handle_Item (Global_Config (Field.Type_Name), Field, Path, Reader_Prefix, Ada_Expr);
      end Handle_Component;

      procedure Handle_Enum
        (Enum_Val      : Enum_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Expr      : Virtual_String)
      is
         pragma Unreferenced (Enum_Val);
         Path_Str : constant Virtual_String := Path_To_Vector_Access_String (Path);
      begin
         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_Discrete'(Description => """
            & Outer.Description
            & """, Default => +"
            & Outer.Default
            & "'Image, Options => [for I in "
            & Outer.Type_Name
            & " => +I'Image])");
         Emit_Reader
           (Reader_Prefix
            & " := "
            & Outer.Type_Name
            & "'Value (VSS.Strings.Conversions.To_UTF_8_String (Data.Get (Prunt.Config.Config_Data_Paths.Vector'["
            & Path_Str
            & "])));");
         Emit_Setter
           ("Data.Set (Prunt.Config.Config_Data_Paths.Vector'[" & Path_Str & "], +(" & Ada_Expr & "'Image));");
      end Handle_Enum;

      procedure Handle_Array
        (Array_Val     : Array_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Prefix    : Virtual_String)
      is
         Loop_Index : constant Virtual_String :=
           "Index_" & Conversions.To_Virtual_String (Trim (Index_Level'Image, Both));
      begin
         Index_Level := @ + 1;

         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_Sequence'(Description => """
            & Outer.Description
            & """, Tabbed => "
            & Virtual_String'(if Array_Val.Tabbed then "True" else "False")
            & ", Children => [for "
            & Loop_Index
            & " in "
            & Array_Val.Index_Type
            & " use +"
            & Loop_Index
            & "'Image => ");

         Emit_Reader ("for " & Loop_Index & " in " & Array_Val.Index_Type & " loop");
         Emit_Setter ("for " & Loop_Index & " in " & Array_Val.Index_Type & " loop");

         Handle_Component
           ((Outer
             with delta
               Type_Name   => Array_Val.Element_Type,
               Description => "",
               --  Avoid duplicated description with nested arrays.
               Default     => Outer.Type_Name & "'" & Outer.Default & "(" & Loop_Index & ")",
               Min         => Array_Val.Min,
               Max         => Array_Val.Max),
            Path & [""" & (+" & Loop_Index & "'Image) & """],
            Reader_Prefix & " (" & Loop_Index & ")",
            Ada_Prefix & " (" & Loop_Index & ")");

         Emit_Setter ("end loop;");
         Emit_Reader ("end loop;");
         Emit_Config_Map ("])");

         Index_Level := @ - 1;
      end Handle_Array;

      procedure Handle_Record
        (Record_Val    : Record_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Prefix    : Virtual_String)
      is
         Fixed_Kind_Str    : Virtual_String;
         Fixed_Desc_Suffix : Virtual_String := "";
      begin
         if Outer.Fixed_Kind /= "" then
            declare
               Fixed_Kind_Split : constant VSS.String_Vectors.Virtual_String_Vector := Outer.Fixed_Kind.Split ('?');
            begin
               if Fixed_Kind_Split.Length = 1 then
                  Fixed_Kind_Str := Fixed_Kind_Split.First_Element;
               elsif Fixed_Kind_Split.Length = 2 then
                  Fixed_Kind_Str :=
                    Fixed_Kind_Split.First_Element
                    & Conversions.To_Virtual_String (Trim (Integer'Image (Index_Level - 1), Both))
                    & Fixed_Kind_Split.Last_Element;
               else
                  raise Constraint_Error;
               end if;
            end;

            if Record_Val.Has_Variant then
               declare
                  Is_First : Boolean := True;
               begin
                  Fixed_Desc_Suffix.Append (" & (if ");
                  for Variant_C in Record_Val.Variants.Iterate loop
                     if not Is_First then
                        Fixed_Desc_Suffix.Append (" elsif ");
                     end if;
                     Fixed_Desc_Suffix.Append (Fixed_Kind_Str & " = " & Variant_Case_Maps.Key (Variant_C));
                     Fixed_Desc_Suffix.Append
                       (" then +""\n" & Variant_Case_Maps.Element (Variant_C).Description & """");
                     Is_First := False;
                  end loop;

                  if not Is_First then
                     Fixed_Desc_Suffix.Append (" else +"""")");
                  else
                     Fixed_Desc_Suffix := "";
                  end if;
               end;
            end if;
         end if;

         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_Sequence'(Tabbed => "
            & Virtual_String'(if Record_Val.Tabbed then "True" else "False")
            & ", Description => """
            & Record_Val.Description
            & """"
            & Fixed_Desc_Suffix
            & ", Children => Prunt.Config.Config_Property_Maps.""&"" (");
         --  Call `&` as a regular function so we can swap the arguments and place the variant part after the
         --  non-variant part. We can not simply place the variant code after the non-variant code generation as we use
         --  a delta aggregate to set the non-variant fields and delta aggregates can not set discriminants, which the
         --  variant code does.

         if Outer.Fixed_Kind /= "" then
            declare
               Is_First : Boolean := True;
            begin
               Emit_Config_Map ("Right => (");

               for Variant_C in Record_Val.Variants.Iterate loop
                  Emit_Config_Map
                    (Virtual_String'(if Is_First then "" else "els")
                     & "if "
                     & Fixed_Kind_Str
                     & " = "
                     & Variant_Case_Maps.Key (Variant_C)
                     & " then [");
                  Emit_Reader
                    (Virtual_String'(if Is_First then "" else "els")
                     & "if "
                     & Fixed_Kind_Str
                     & " = "
                     & Variant_Case_Maps.Key (Variant_C)
                     & " then");
                  Emit_Reader
                    (Reader_Prefix
                     & " := ("
                     & Record_Val.Discriminant
                     & " => "
                     & Variant_Case_Maps.Key (Variant_C)
                     & ", others => <>);");
                  Emit_Setter
                    (Virtual_String'(if Is_First then "" else "els")
                     & "if "
                     & Ada_Prefix
                     & "."
                     & Record_Val.Discriminant
                     & " = "
                     & Variant_Case_Maps.Key (Variant_C)
                     & " then");

                  Emit_Setter ("null;");

                  declare
                     Components renames Variant_Case_Maps.Element (Variant_C).Components;
                     Is_First : Boolean := True;
                  begin
                     for Component_C in Components.Iterate loop
                        Emit_Config_Map
                          (Virtual_String'(if Is_First then "" else ", ")
                           & """"
                           & Component_Data_Maps.Key (Component_C)
                           & """ =>");
                        Handle_Component
                          (Component_Data_Maps.Element (Component_C),
                           Path & ["Children", Component_Data_Maps.Key (Component_C)],
                           Reader_Prefix & "." & Component_Data_Maps.Key (Component_C),
                           Ada_Prefix & "." & Component_Data_Maps.Key (Component_C));
                        Is_First := False;
                     end loop;
                  end;

                  Emit_Config_Map ("]");

                  Is_First := False;
               end loop;

               Emit_Reader ("else");
               Emit_Reader ("raise Constraint_Error;");
               Emit_Reader ("end if;");
               Emit_Config_Map ("else raise Constraint_Error),");
               Emit_Setter ("else");
               Emit_Setter ("raise Constraint_Error;");
               Emit_Setter ("end if;");
            end;
         elsif Record_Val.Has_Variant then
            declare
               Is_First : Boolean := True;
            begin
               Emit_Config_Map
                 ("Right => ["""
                  & Record_Val.Discriminant
                  & """ => Prunt.Config.Config_Property_Parameters_Variant'(Default => """
                  & Record_Val.Discriminant_Default
                  & """, Description => """", Children => [");
               --  Call `&` as a regular function so we can swap the arguments and place the variant part after the
               --  non-variant part. We can not simply place this code after the non-variant code generation as we use
               --  a delta aggregate to set the non-variant fields and delta aggregates can not set discriminants,
               --  which this code does.

               for Variant_C in Record_Val.Variants.Iterate loop
                  Emit_Config_Map
                    (Virtual_String'(if Is_First then "" else ", ")
                     & """"
                     & Variant_Case_Maps.Key (Variant_C)
                     & """ => Prunt.Config.Config_Property_Parameters_Sequence'(Tabbed => "
                     & Virtual_String'(if Record_Val.Tabbed then "True" else "False")
                     & ", Description => """
                     & Variant_Case_Maps.Element (Variant_C).Description
                     & """, Children => [");
                  Emit_Reader
                    (Virtual_String'(if Is_First then "" else "els")
                     & "if Data.Get (Prunt.Config.Config_Data_Paths.Vector'["
                     & Path_To_Vector_Access_String (Path & [Record_Val.Discriminant, "Selected"])
                     & "]) = """
                     & Variant_Case_Maps.Key (Variant_C)
                     & """ then "
                     & Reader_Prefix
                     & " := ("
                     & Record_Val.Discriminant
                     & " => "
                     & Variant_Case_Maps.Key (Variant_C)
                     & ", others => <>);");
                  Emit_Setter
                    (Virtual_String'(if Is_First then "" else "els")
                     & "if "
                     & Ada_Prefix
                     & "."
                     & Record_Val.Discriminant
                     & " = "
                     & Variant_Case_Maps.Key (Variant_C)
                     & " then");

                  Emit_Setter ("null;");

                  declare
                     Component renames Variant_Case_Maps.Element (Variant_C).Components;
                     Is_First : Boolean := True;
                  begin
                     for Component_C in Component.Iterate loop
                        Emit_Config_Map
                          (Virtual_String'(if Is_First then "" else ", ")
                           & """"
                           & Component_Data_Maps.Key (Component_C)
                           & """ =>");
                        Handle_Component
                          (Component_Data_Maps.Element (Component_C),
                           Path
                           & [Record_Val.Discriminant,
                              "Children",
                              Variant_Case_Maps.Key (Variant_C),
                              Component_Data_Maps.Key (Component_C)],
                           Reader_Prefix
                           & "."
                           & Component_Data_Maps.Key (Component_C),
                           Ada_Prefix
                           & "."
                           & Component_Data_Maps.Key (Component_C));
                        Is_First := False;
                     end loop;
                  end;

                  Is_First := False;

                  Emit_Config_Map ("])");
               end loop;

               Emit_Reader ("else");
               Emit_Reader ("raise Constraint_Error;");
               Emit_Reader ("end if;");
               Emit_Config_Map ("])],");
               Emit_Setter ("else");
               Emit_Setter ("raise Constraint_Error;");
               Emit_Setter ("end if;");
            end;
         else
            Emit_Config_Map ("Right => [],");
         end if;

         Emit_Config_Map ("Left => [");

         if Record_Val.Components.Is_Empty then
            if not Record_Val.Has_Variant then
               Emit_Setter ("null;");
            end if;
         else
            declare
               Is_First : Boolean := True;
            begin
               for C in Record_Val.Components.Iterate loop
                  Emit_Config_Map
                    (Virtual_String'(if Is_First then "" else ",") & """" & Component_Data_Maps.Key (C) & """ =>");

                  Handle_Component
                    (Component_Data_Maps.Element (C),
                     Path & [Component_Data_Maps.Key (C)],
                     Reader_Prefix & "." & Component_Data_Maps.Key (C),
                     Ada_Prefix & "." & Component_Data_Maps.Key (C));

                  Is_First := False;
               end loop;
            end;
         end if;

         Emit_Config_Map ("]");
         Emit_Config_Map ("))");
      end Handle_Record;

      procedure Handle_Item
        (Item          : Config_Type;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Prefix    : Virtual_String) is
      begin
         case Item.Kind is
            when Record_Kind  =>
               Handle_Record (Item.Record_Value, Outer, Path, Reader_Prefix, Ada_Prefix);

            when Array_Kind   =>
               Handle_Array (Item.Array_Value, Outer, Path, Reader_Prefix, Ada_Prefix);

            when Enum_Kind    =>
               Handle_Enum (Item.Enum_Value, Outer, Path, Reader_Prefix, Ada_Prefix);

            when Boolean_Kind =>
               Handle_Boolean (Item.Boolean_Value, Outer, Path, Reader_Prefix, Ada_Prefix);

            when Integer_Kind =>
               Handle_Integer (Item.Integer_Value, Outer, Path, Reader_Prefix, Ada_Prefix);

            when Float_Kind   =>
               Handle_Float (Item.Float_Value, Outer, Path, Reader_Prefix, Ada_Prefix);

            when Ratio_Kind   =>
               Handle_Ratio (Item.Ratio_Value, Outer, Path, Reader_Prefix, Ada_Prefix);
         end case;
      end Handle_Item;
   begin

      if not Ada.Directories.Exists (Out_Dir) then
         Ada.Directories.Create_Directory (Out_Dir);
      end if;

      if Data.Root_Type /= "" and then Data.Config.Contains (Data.Root_Type) then
         Emit_Config_Map ("pragma Style_Checks (Off);");
         Emit_Config_Map
           ("--  This file is automatically generated based on the contents of "
            & Conversions.To_Virtual_String (Filename));
         Emit_Config_Map ("--  Run config_codegen to regenerate this file.");
         Emit_Config_Map ("pragma Warnings (Off, ""no entities of * are referenced"");");
         Emit_Config_Map ("with VSS.Characters.Latin;");
         Emit_Config_Map ("with Prunt.Config;");
         Emit_Config_Map ("pragma Warnings (On, ""no entities of * are referenced"");");
         Emit_Config_Map ("separate (" & Data.Name & ")");
         Emit_Config_Map ("function Build_Schema return Prunt.Config.Config_Property_Maps.Map is");
         Emit_Config_Map ("pragma Unsuppress (All_Checks);");
         Emit_Config_Map ("pragma Warnings (Off, ""use clause for private type * has no effect"");");
         Emit_Config_Map ("pragma Warnings (Off, ""use clause for type * has no effect"");");
         Emit_Config_Map ("use type Prunt.Config.Config_Property_Maps.Map;");
         Emit_Config_Map ("pragma Warnings (On, ""use clause for type * has no effect"");");
         Emit_Config_Map ("pragma Warnings (On, ""use clause for private type * has no effect"");");
         Emit_Config_Map ("begin");
         Emit_Config_Map ("pragma Extensions_Allowed (On);");
         Emit_Config_Map ("return");

         Emit_Reader ("pragma Style_Checks (Off);");
         Emit_Reader
           ("--  This file is automatically generated based on the contents of "
            & Conversions.To_Virtual_String (Filename));
         Emit_Reader ("--  Run config_codegen to regenerate this file.");
         Emit_Reader ("pragma Warnings (Off, ""no entities of * are referenced"");");
         Emit_Reader ("with VSS.Characters.Latin;");
         Emit_Reader ("pragma Warnings (On, ""no entities of * are referenced"");");
         Emit_Reader ("separate (" & Data.Name & ")");
         Emit_Reader
           ("function Config_Data_To_User_Config (Data : Prunt.Config.Config_Data) return User_Config is");
         Emit_Reader ("pragma Unsuppress (All_Checks);");
         Emit_Reader ("begin");
         Emit_Reader ("pragma Extensions_Allowed (On);");
         Emit_Reader ("return Result : User_Config do");

         Emit_Setter ("pragma Style_Checks (Off);");
         Emit_Setter
           ("--  This file is automatically generated based on the contents of "
            & Conversions.To_Virtual_String (Filename));
         Emit_Setter ("--  Run config_codegen to regenerate this file.");
         Emit_Setter ("pragma Warnings (Off, ""no entities of * are referenced"");");
         Emit_Setter ("with VSS.Characters.Latin;");
         Emit_Setter ("pragma Warnings (On, ""no entities of * are referenced"");");
         Emit_Setter ("separate (" & Data.Name & ")");
         Emit_Setter
           ("procedure User_Config_To_Config_Data (Data : Prunt.Config.Config_Data; Config : User_Config) is");
         Emit_Setter ("pragma Unsuppress (All_Checks);");
         Emit_Setter ("pragma Extensions_Allowed (On);");
         Emit_Setter ("begin");

         Handle_Item
           (Item          => Data.Config (Data.Root_Type),
            Outer         => (others => <>),
            Path          => [],
            Reader_Prefix => "Result",
            Ada_Prefix    => "Config");

         Emit_Setter ("Data.Save;");
         Emit_Setter ("end User_Config_To_Config_Data;");

         Emit_Reader ("end return;");
         Emit_Reader ("end Config_Data_To_User_Config;");

         Emit_Config_Map (".Children;");
         Emit_Config_Map ("end Build_Schema;");


         Write_File
           (Ada.Directories.Compose
              (Containing_Directory => Out_Dir, Name => Ada.Directories.Base_Name (Filename) & "-build_schema.adb"),
            Config_Map_Out);
         Write_File
           (Ada.Directories.Compose
              (Containing_Directory => Out_Dir,
               Name                 => Ada.Directories.Base_Name (Filename) & "-config_data_to_user_config.adb"),
            Reader_Out);
         Write_File
           (Ada.Directories.Compose
              (Containing_Directory => Out_Dir,
               Name                 => Ada.Directories.Base_Name (Filename) & "-user_config_to_config_data.adb"),
            Setter_Out);
      end if;

      if not Data.Gcode_Commands.Is_Empty then
         Generate_Gcode_Dispatch (Filename, Data);
         Generate_Gcode_Commands_List (Filename, Data);
      end if;
   end Generate_Files;

end Config_Generator;
