--  Part of the Prunt Motion Controller
--
--  Copyright (C) 2026 Liam Powell (liam@prunt3d.com)
--
--  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
--  documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
--  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
--  permit persons to whom the Software is furnished to do so, subject to the following conditions:
--
--  The above copyright notice and this permission notice (including the next paragraph) shall be included in all
--  copies or substantial portions of the Software.
--
--  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
--  THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
--  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
--  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
--  SOFTWARE.
--------------------------------------------------

--  If you're reading this file then there's a good chance that you're wondering why the `Config_Data_To_User_Config`
--  functions are generating some convoluted nonsense with explicit statements instead of a nice, easy to generate
--  expression like everything else. The reason is that GNAT is broken and will generate bogus visibility errors when
--  using an aggregate expression to generate an array: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=124282

with Ada.Directories;
with Ada.Strings;       use Ada.Strings;
with Ada.Strings.Fixed; use Ada.Strings.Fixed;
with Ada.Text_IO;       use Ada.Text_IO;
with GNAT.Source_Info;
with VSS.Characters.Latin;
with VSS.Strings.Conversions;

package body Config_Generator is

   pragma Extensions_Allowed (On);

   Out_Dir : constant String := "generated_src_modules";

   procedure Write_File (Filename : String; Content : Virtual_String) is
      File : Ada.Text_IO.File_Type;
   begin
      Put_Line ("Writing file: " & Filename);
      Create (File, Out_File, Filename);
      Put (File, Conversions.To_UTF_8_String (Content));
      Close (File);
   end Write_File;

   procedure Generate_Gcode_Dispatch (Filename : String; Data : Module_Data) is
      Letters         : String_Vectors.Vector;
      Current_Map_Out : Virtual_String;

      function Uses_Gcode_Args return Boolean is
      begin
         for C in Data.Gcode_Commands.Iterate loop
            if not Gcode_Command_Maps.Element (C).Is_Empty then
               return True;
            end if;
         end loop;

         return False;
      end Uses_Gcode_Args;

      function No_User_Arguments_Condition return Virtual_String is
         Result : Virtual_String;
         First  : Boolean := True;
      begin
         for Arg in Character range 'A' .. 'Z' loop
            if Arg not in 'G' | 'M' then
               if not First then
                  Result.Append (" and then ");
               end if;

               Result.Append ("Args.Kind ('");
               Result.Append (Conversions.To_Virtual_String (String'(1 => Arg)));
               Result.Append ("') = Gcode_Arguments.Non_Existent_Kind");
               First := False;
            end if;
         end loop;

         return Result;
      end No_User_Arguments_Condition;

      procedure Emit
        (Text               : Virtual_String;
         Location           : String  := GNAT.Source_Info.Source_Location;
         Trailing_Line_Feed : Boolean := True) is
      begin
         Current_Map_Out.Append (Text);
         Current_Map_Out.Append (" --  " & Conversions.To_Virtual_String (Location));
         if Trailing_Line_Feed then
            Current_Map_Out.Append (VSS.Characters.Latin.Line_Feed);
         end if;
      end Emit;

   begin
      Emit ("pragma Style_Checks (Off);");
      Emit
        ("--  This file is automatically generated based on the contents of "
         & Conversions.To_Virtual_String (Filename));
      Emit ("--  Run config_codegen to regenerate this file.");
      Emit ("pragma Warnings (Off, ""no entities of * are referenced"");");
      Emit ("pragma Warnings (Off, ""unit * is not referenced"");");
      Emit ("with Prunt.Gcode_Arguments;");
      Emit ("with VSS.Characters.Latin;");
      Emit ("pragma Warnings (On, ""unit * is not referenced"");");
      Emit ("pragma Warnings (On, ""no entities of * are referenced"");");
      Emit ("separate (" & Data.Name & ")");
      Emit ("overriding");
      Emit
        ("procedure Gcode_Dispatch "
         & "(This : Module_Instance; Self_Ref : My_Modules.Module_Instance_Shared_Pointers.Ref; "
         & "Args : in out Gcode_Arguments.Arguments; "
         & "Planner : Prunt.Module_Types.Planner_Interface'Class; "
         & "Command_Identifier : Prunt.Module_Types.Gcode_Command_Identifier) is");
      Emit ("pragma Unsuppress (All_Checks);");
      if Uses_Gcode_Args then
         Emit ("use type Prunt.Gcode_Arguments.Argument_Kind;");
      else
         Emit ("pragma Unreferenced (Args);");
      end if;
      Emit ("begin");
      Emit ("pragma Annotate (Xcov, Exempt_On, ""Generated G-code dispatch."");");
      Emit ("pragma Extensions_Allowed (On);");
      Emit ("case Command_Identifier.Argument is");

      for C in Data.Gcode_Commands.Iterate loop
         declare
            Key : constant Gcode_Key := Gcode_Command_Maps.Key (C);
         begin
            if not Letters.Contains (Key.Letter) then
               Letters.Append (Key.Letter);
            end if;
         end;
      end loop;

      for L of Letters loop
         Emit ("when '" & L & "' =>");
         Emit ("case Command_Identifier.Number is");

         declare
            Numbers : String_Vectors.Vector;
         begin
            for C in Data.Gcode_Commands.Iterate loop
               declare
                  Key     : constant Gcode_Key := Gcode_Command_Maps.Key (C);
                  Num_Str : constant Virtual_String := Conversions.To_Virtual_String (Trim (Key.Number'Image, Both));
               begin
                  if Key.Letter = L and then not Numbers.Contains (Num_Str) then
                     Numbers.Append (Num_Str);
                  end if;
               end;
            end loop;

            for N of Numbers loop
               Emit ("when " & N & " =>");

               declare
                  Variants : constant Config_Types.Gcode_Command_Vectors.Vector :=
                    Data.Gcode_Commands.Element
                      ((Letter => L, Number => Integer'Value (Conversions.To_UTF_8_String (N))));
               begin

                  declare
                     First_Var : Boolean := True;
                  begin
                     for Variant of Variants loop
                        declare
                           Conditions : Virtual_String;
                           First_Cond : Boolean := True;
                        begin
                           for Arg_C in Variant.Arguments.Iterate loop
                              declare
                                 Arg_Name : constant Virtual_String := Gcode_Argument_Maps.Key (Arg_C);
                                 Arg_Data : constant Gcode_Argument_Data := Gcode_Argument_Maps.Element (Arg_C);
                                 Checks   : Virtual_String;

                                 procedure Add_Check (K : Virtual_String) is
                                 begin
                                    if Checks /= "" then
                                       Checks.Append (" or else ");
                                    end if;
                                    Checks.Append ("Args.Kind ('" & Arg_Name & "') = " & K);
                                 end Add_Check;
                              begin
                                 if Arg_Name /= "This"
                                   and then Arg_Name /= "Self_Ref"
                                   and then Arg_Name /= "Planner"
                                 then
                                    if Arg_Data.Arg_Kinds (Config_Types.Integer_Kind) then
                                       Add_Check ("Gcode_Arguments.Integer_Kind");
                                    end if;
                                    if Arg_Data.Arg_Kinds (Config_Types.Float_Kind) then
                                       Add_Check ("Gcode_Arguments.Float_Kind");
                                    end if;
                                    if Arg_Data.Arg_Kinds (Config_Types.String_Kind) then
                                       Add_Check ("Gcode_Arguments.String_Kind");
                                    end if;
                                    if Arg_Data.Arg_Kinds (Config_Types.Not_Present_Kind) then
                                       Add_Check ("Gcode_Arguments.Non_Existent_Kind");
                                    end if;
                                    if Arg_Data.Arg_Kinds (Config_Types.No_Value_Kind) then
                                       Add_Check ("Gcode_Arguments.No_Value_Kind");
                                    end if;

                                    if Checks /= "" then
                                       if not First_Cond then
                                          Conditions.Append (" and then ");
                                       end if;
                                       Conditions.Append ("(" & Checks & ")");
                                       First_Cond := False;
                                    end if;
                                 end if;
                              end;
                              end loop;

                           for Arg in Character range 'A' .. 'Z' loop
                              if Arg not in 'G' | 'M' then
                                 declare
                                    Arg_Name : constant Virtual_String :=
                                      Conversions.To_Virtual_String (String'(1 => Arg));
                                 begin
                                    if not Variant.Arguments.Contains (Arg_Name) then
                                       if not First_Cond then
                                          Conditions.Append (" and then ");
                                       end if;

                                       Conditions.Append
                                         ("Args.Kind ('"
                                          & Arg_Name
                                          & "') = Gcode_Arguments.Non_Existent_Kind");
                                       First_Cond := False;
                                    end if;
                                 end;
                              end if;
                           end loop;

                           if Conditions = "" then
                              Conditions := No_User_Arguments_Condition;
                           end if;

                           Emit (Virtual_String'(if First_Var then "" else "els") & "if " & Conditions & " then");

                           declare
                              Args_Call : Virtual_String;
                              First_Arg : Boolean := True;
                           begin
                              for Arg_C in
                                Variant.Arguments.Iterate
                                when Gcode_Argument_Maps.Key (Arg_C) /= "This"
                                and then Gcode_Argument_Maps.Key (Arg_C) /= "Self_Ref"
                                and then Gcode_Argument_Maps.Key (Arg_C) /= "Planner"
                              loop
                                 declare
                                    Arg_Name     : constant Virtual_String := Gcode_Argument_Maps.Key (Arg_C);
                                    Arg_Data     : constant Gcode_Argument_Data := Gcode_Argument_Maps.Element (Arg_C);
                                    Type_Name_St : constant String := Conversions.To_UTF_8_String (Arg_Data.Type_Name);
                                    Val_Expr     : Virtual_String;
                                 begin
                                    if not First_Arg then
                                       Args_Call.Append (", ");
                                    end if;

                                    if Index (Type_Name_St, "Gcode_Float_Or_No_Value") > 0 then
                                       Val_Expr :=
                                         "(case Args.Kind ('"
                                         & Arg_Name
                                         & "') is when Gcode_Arguments.No_Value_Kind => "
                                         & "(if Args.Consume_No_Value ('"
                                         & Arg_Name
                                         & "') then (Kind => Prunt.Module_Types.Gcode_No_Value_Present) "
                                         & "else (Kind => Prunt.Module_Types.Gcode_No_Value_Present)), "
                                         & "when others => "
                                         & "(Kind => Prunt.Module_Types.Gcode_Value_Present, "
                                         & "Value => Args.Consume_Float ('"
                                         & Arg_Name
                                         & "')))";
                                       if Arg_Data.Default /= "" then
                                          raise Constraint_Error
                                            with
                                              "Gcode_Float_Or_No_Value can not have default ("
                                              & L'Image
                                              & N'Image
                                              & ": "
                                              & Variant'Image
                                              & ")";
                                       end if;
                                    elsif Index (Type_Name_St, "Gcode_Integer_Or_No_Value") > 0 then
                                       Val_Expr :=
                                         "(case Args.Kind ('"
                                         & Arg_Name
                                         & "') is when Gcode_Arguments.No_Value_Kind => "
                                         & "(if Args.Consume_No_Value ('"
                                         & Arg_Name
                                         & "') then (Kind => Prunt.Module_Types.Gcode_No_Value_Present) "
                                         & "else (Kind => Prunt.Module_Types.Gcode_No_Value_Present)), "
                                         & "when others => "
                                         & "(Kind => Prunt.Module_Types.Gcode_Value_Present, "
                                         & "Value => Args.Consume_Integer ('"
                                         & Arg_Name
                                         & "')))";
                                       if Arg_Data.Default /= "" then
                                          raise Constraint_Error
                                            with
                                              "Gcode_Integer_Or_No_Value can not have default ("
                                              & L'Image
                                              & N'Image
                                              & ": "
                                              & Variant'Image
                                              & ")";
                                       end if;
                                    elsif Index (Type_Name_St, "Optional_Float_Or_No_Value") > 0 then
                                       Val_Expr :=
                                         "(case Args.Kind ('"
                                         & Arg_Name
                                         & "') is when Gcode_Arguments.Non_Existent_Kind => "
                                         & "(Kind => Prunt.Module_Types.Gcode_Value_Not_Present), "
                                         & "when Gcode_Arguments.No_Value_Kind => "
                                         & "(if Args.Consume_No_Value ('"
                                         & Arg_Name
                                         & "') then (Kind => Prunt.Module_Types.Gcode_No_Value_Present) "
                                         & "else (Kind => Prunt.Module_Types.Gcode_No_Value_Present)), "
                                         & "when others => "
                                         & "(Kind => Prunt.Module_Types.Gcode_Value_Present, "
                                         & "Value => Args.Consume_Float ('"
                                         & Arg_Name
                                         & "')))";
                                       if Arg_Data.Default /= "" then
                                          raise Constraint_Error
                                            with
                                              "Optional_Float_Or_No_Value can not have default ("
                                              & L'Image
                                              & N'Image
                                              & ": "
                                              & Variant'Image
                                              & ")";
                                       end if;
                                    elsif Index (Type_Name_St, "Optional_Integer_Or_No_Value") > 0 then
                                       Val_Expr :=
                                         "(case Args.Kind ('"
                                         & Arg_Name
                                         & "') is when Gcode_Arguments.Non_Existent_Kind => "
                                         & "(Kind => Prunt.Module_Types.Gcode_Value_Not_Present), "
                                         & "when Gcode_Arguments.No_Value_Kind => "
                                         & "(if Args.Consume_No_Value ('"
                                         & Arg_Name
                                         & "') then (Kind => Prunt.Module_Types.Gcode_No_Value_Present) "
                                         & "else (Kind => Prunt.Module_Types.Gcode_No_Value_Present)), "
                                         & "when others => "
                                         & "(Kind => Prunt.Module_Types.Gcode_Value_Present, "
                                         & "Value => Args.Consume_Integer ('"
                                         & Arg_Name
                                         & "')))";
                                       if Arg_Data.Default /= "" then
                                          raise Constraint_Error
                                            with
                                              "Optional_Integer_Or_No_Value can not have default ("
                                              & L'Image
                                              & N'Image
                                              & ": "
                                              & Variant'Image
                                              & ")";
                                       end if;
                                    elsif Index (Type_Name_St, "Optional_Float") > 0 then
                                       Val_Expr :=
                                         "(if Args.Kind ('"
                                         & Arg_Name
                                         & "') /= Gcode_Arguments.Non_Existent_Kind then "
                                         & "(Present => True, Value => Args.Consume_Float ('"
                                         & Arg_Name
                                         & "')) else (Present => False))";
                                       if Arg_Data.Default /= "" then
                                          raise Constraint_Error
                                            with
                                              "Optional_Float can not have default ("
                                              & L'Image
                                              & N'Image
                                              & ": "
                                              & Variant'Image
                                              & ")";
                                       end if;
                                    elsif Index (Type_Name_St, "Optional_Integer") > 0 then
                                       Val_Expr :=
                                         "(if Args.Kind ('"
                                         & Arg_Name
                                         & "') /= Gcode_Arguments.Non_Existent_Kind then "
                                         & "(Present => True, Value => Args.Consume_Integer ('"
                                         & Arg_Name
                                         & "')) else (Present => False))";
                                       if Arg_Data.Default /= "" then
                                          raise Constraint_Error
                                            with
                                              "Optional_Integer can not have default ("
                                              & L'Image
                                              & N'Image
                                              & ": "
                                              & Variant'Image
                                              & ")";
                                       end if;
                                    elsif Index (Type_Name_St, "Optional_String") > 0 then
                                       Val_Expr :=
                                         "(if Args.Kind ('"
                                         & Arg_Name
                                         & "') /= Gcode_Arguments.Non_Existent_Kind then "
                                         & "(Present => True, Value => Args.Consume_String ('"
                                         & Arg_Name
                                         & "')) else (Present => False))";
                                       if Arg_Data.Default /= "" then
                                          raise Constraint_Error
                                            with
                                              "Optional_String can not have default ("
                                              & L'Image
                                              & N'Image
                                              & ": "
                                              & Variant'Image
                                              & ")";
                                       end if;
                                    elsif Index (Type_Name_St, "Optional_No_Value") > 0 then
                                       Val_Expr :=
                                         "(Present => Args.Consume_No_Value_Or_False ('" & Arg_Name & "'))";
                                       if Arg_Data.Default /= "" then
                                          raise Constraint_Error
                                            with
                                              "Optional_No_Value can not have default ("
                                              & L'Image
                                              & N'Image
                                              & ": "
                                              & Variant'Image
                                              & ")";
                                       end if;
                                    elsif Index (Type_Name_St, "No_Value") > 0 then
                                       Val_Expr :=
                                         "(if Args.Consume_No_Value ('"
                                         & Arg_Name
                                         & "') then (null record) else (null record))";
                                       if Arg_Data.Default /= "" then
                                          raise Constraint_Error
                                            with
                                              "No_Value can not have default ("
                                              & L'Image
                                              & N'Image
                                              & ": "
                                              & Variant'Image
                                              & ")";
                                       end if;
                                    elsif Index (Type_Name_St, "Dimensionless") > 0 then
                                       if Arg_Data.Default /= "" then
                                          Val_Expr :=
                                            "Args.Consume_Float_Or_Default ('"
                                            & Arg_Name
                                            & "', "
                                            & Arg_Data.Default
                                            & ")";
                                       else
                                          Val_Expr := "Args.Consume_Float ('" & Arg_Name & "')";
                                       end if;
                                    elsif Index (Type_Name_St, "Argument_Integer") > 0 then
                                       if Arg_Data.Default /= "" then
                                          Val_Expr :=
                                            "Args.Consume_Integer_Or_Default ('"
                                            & Arg_Name
                                            & "', "
                                            & Arg_Data.Default
                                            & ")";
                                       else
                                          Val_Expr := "Args.Consume_Integer ('" & Arg_Name & "')";
                                       end if;
                                    elsif Index (Type_Name_St, "String") > 0 then
                                       if Arg_Data.Default /= "" then
                                          Val_Expr :=
                                            "Args.Consume_String_Or_Default ('"
                                            & Arg_Name
                                            & "', "
                                            & Arg_Data.Default
                                            & ")";
                                       else
                                          Val_Expr := "Args.Consume_String ('" & Arg_Name & "')";
                                       end if;
                                    else
                                       raise Constraint_Error
                                         with
                                           "Unhandled argument type ("
                                           & L'Image
                                           & N'Image
                                           & ": "
                                           & Variant'Image
                                           & ")";
                                    end if;

                                    Args_Call.Append (Arg_Name & " => " & Val_Expr);
                                    First_Arg := False;
                                 end;
                              end loop;

                              declare
                                 Call_Prefix : Virtual_String := "";
                              begin
                                 if Variant.Has_This then
                                    Call_Prefix.Append ("This => This");
                                 end if;

                                 if Variant.Has_Self_Ref then
                                    if Call_Prefix /= "" then
                                       Call_Prefix.Append (", ");
                                    end if;
                                    Call_Prefix.Append ("Self_Ref => Self_Ref");
                                 end if;

                                 if Variant.Has_Planner then
                                    if Call_Prefix /= "" then
                                       Call_Prefix.Append (", ");
                                    end if;
                                    Call_Prefix.Append ("Planner => Planner");
                                 end if;

                                 if Args_Call /= "" then
                                    if Call_Prefix /= "" then
                                       Call_Prefix.Append (", ");
                                       Call_Prefix.Append (Args_Call);
                                    else
                                       Call_Prefix := Args_Call;
                                    end if;
                                 end if;

                                 Emit (Variant.Name & " (" & Call_Prefix & ");");
                              end;
                           end;

                           First_Var := False;
                        end;
                     end loop;
                     Emit ("else");
                     Emit
                       ("raise Prunt.Module_Types.Gcode_Bad_Inputs_Error "
                        & "with ""No matching G-code variant found."";");
                     Emit ("end if;");
                  end;
               end;
            end loop;

            Emit ("when others =>");
            Emit ("raise Prunt.Module_Types.Gcode_Bad_Inputs_Error with ""Unknown G-code command."";");
         end;
         Emit ("end case;");
      end loop;

      Emit ("when others =>");
      Emit ("raise Prunt.Module_Types.Gcode_Bad_Inputs_Error with ""Unknown G-code command identifier."";");
      Emit ("end case;");
      Emit ("pragma Annotate (Xcov, Exempt_Off);");
      Emit ("pragma Style_Checks (On);");
      Emit (Text => "end Gcode_Dispatch;", Trailing_Line_Feed => False);

      Write_File
        (Ada.Directories.Compose
           (Containing_Directory => Out_Dir, Name => Ada.Directories.Base_Name (Filename) & "-gcode_dispatch.adb"),
         Current_Map_Out);
   end Generate_Gcode_Dispatch;

   procedure Generate_Gcode_Commands_List (Filename : String; Data : Module_Data) is
      Current_Map_Out : Virtual_String;

      procedure Emit
        (Text               : Virtual_String;
         Location           : String  := GNAT.Source_Info.Source_Location;
         Trailing_Line_Feed : Boolean := True) is
      begin
         Current_Map_Out.Append (Text);
         Current_Map_Out.Append (" --  " & Conversions.To_Virtual_String (Location));
         if Trailing_Line_Feed then
            Current_Map_Out.Append (VSS.Characters.Latin.Line_Feed);
         end if;
      end Emit;
   begin
      Emit ("pragma Style_Checks (Off);");
      Emit
        ("--  This file is automatically generated based on the contents of "
         & Conversions.To_Virtual_String (Filename));
      Emit ("--  Run config_codegen to regenerate this file.");
      Emit ("pragma Warnings (Off, ""no entities of * are referenced"");");
      Emit ("pragma Warnings (Off, ""unit * is not referenced"");");
      Emit ("with Prunt.Gcode_Arguments;");
      Emit ("with VSS.Characters.Latin;");
      Emit ("pragma Warnings (On, ""unit * is not referenced"");");
      Emit ("pragma Warnings (On, ""no entities of * are referenced"");");
      Emit ("separate (" & Data.Name & ")");
      Emit ("overriding");
      Emit ("function Gcode_Commands (This : Module) return Prunt.Module_Types.Gcode_Command_Vectors.Vector is");
      Emit ("pragma Unsuppress (All_Checks);");
      Emit ("begin");
      Emit ("return");
      Emit ("[");

      declare
         First_Cmd : Boolean := True;
      begin
         for C in Data.Gcode_Commands.Iterate loop
            declare
               Key : constant Gcode_Key := Gcode_Command_Maps.Key (C);
            begin
               for Info_Idx in Gcode_Command_Maps.Element (C).First_Index .. Gcode_Command_Maps.Element (C).Last_Index
               loop
                  declare
                     Info : constant Gcode_Command_Data := Gcode_Command_Maps.Element (C) (Info_Idx);
                  begin
                     if not First_Cmd then
                        Emit (",");
                     end if;
                     Emit
                       ("(Identifier  => ('"
                        & Key.Letter
                        & "', "
                        & Conversions.To_Virtual_String (Trim (Key.Number'Image, Both))
                        & "),");
                     Emit (" Name        => """ & Info.Name & """,");
                     Emit (" Description => """ & Info.Description & """,");
                     Emit (" Arguments   =>");

                     if Info.Arguments.Is_Empty then
                        Emit ("[])");
                     else
                        Emit ("[");
                        declare
                           First_Arg : Boolean := True;
                        begin
                           for Arg_C in Info.Arguments.Iterate loop
                              declare
                                 Arg_Name : constant Virtual_String := Gcode_Argument_Maps.Key (Arg_C);
                                 Arg_Data : constant Gcode_Argument_Data := Gcode_Argument_Maps.Element (Arg_C);
                                 Kinds    : Virtual_String;

                                 procedure Add_K (K : Virtual_String) is
                                 begin
                                    if Kinds /= "" then
                                       Kinds.Append (", ");
                                    end if;
                                    Kinds.Append (K & " => True");
                                 end Add_K;
                              begin
                                 if Arg_Name /= "This"
                                   and then Arg_Name /= "Self_Ref"
                                   and then Arg_Name /= "Planner"
                                 then
                                    if not First_Arg then
                                       Emit (",");
                                    end if;

                                    for Kind in Config_Types.Gcode_Argument_Kind loop
                                       if Arg_Data.Arg_Kinds (Kind) then
                                          case Kind is
                                             when Config_Types.Integer_Kind     =>
                                                Add_K ("Gcode_Arguments.Integer_Kind");

                                             when Config_Types.Float_Kind       =>
                                                Add_K ("Gcode_Arguments.Float_Kind");

                                             when Config_Types.String_Kind      =>
                                                Add_K ("Gcode_Arguments.String_Kind");

                                             when Config_Types.No_Value_Kind    =>
                                                Add_K ("Gcode_Arguments.No_Value_Kind");

                                             when Config_Types.Not_Present_Kind =>
                                                Add_K ("Gcode_Arguments.Non_Existent_Kind");
                                          end case;
                                       end if;
                                    end loop;

                                    if Kinds /= "" then
                                       Kinds.Append (", ");
                                    end if;
                                    Kinds.Append ("others => False");

                                    Emit
                                      ("'"
                                       & Arg_Name
                                       & "' => (Allowed_Kinds => ["
                                       & Kinds
                                       & "], Description => """
                                       & Arg_Data.Description
                                       & """)");
                                    First_Arg := False;
                                 end if;
                              end;
                           end loop;
                        end;
                        Emit ("])");
                     end if;

                     First_Cmd := False;
                  end;
               end loop;
            end;
         end loop;
      end;

      Emit ("];");
      Emit ("pragma Style_Checks (On);");
      Emit (Text => "end Gcode_Commands;", Trailing_Line_Feed => False);

      Write_File
        (Ada.Directories.Compose
           (Containing_Directory => Out_Dir, Name => Ada.Directories.Base_Name (Filename) & "-gcode_commands.adb"),
         Current_Map_Out);
   end Generate_Gcode_Commands_List;

   procedure Generate_Files (Filename : String; Data : Module_Data; Global_Config : Config_Maps.Map) is
      Config_Map_Out, Reader_Out, Setter_Out : Virtual_String := "";

      Path_Type_Declarations       : Virtual_String := "";
      Path_Subprogram_Declarations : Virtual_String := "";
      Path_Private_Declarations    : Virtual_String := "";
      Path_Subprogram_Bodies       : Virtual_String := "";
      Path_Has_Arrays              : Boolean := False;
      Path_Node_Count              : Natural := 0;

      Index_Level : Natural := 0;

      function Expand_Index_Level (Expression : Virtual_String) return Virtual_String is
         Expression_String    : constant String := Conversions.To_UTF_8_String (Expression);
         Result              : Virtual_String := "";
         Question_Run_Length : Natural := 0;

         procedure Flush_Question_Run is
            Target_Index_Level : Natural;
         begin
            if Question_Run_Length = 0 then
               return;
            end if;

            if Index_Level < Question_Run_Length then
               raise Constraint_Error with "Index placeholder exceeds available array nesting.";
            end if;

            Target_Index_Level := Index_Level - Question_Run_Length;
            Result.Append (Conversions.To_Virtual_String (Trim (Integer'Image (Target_Index_Level), Both)));
            Question_Run_Length := 0;
         end Flush_Question_Run;
      begin
         if Expression = "" then
            return "";
         end if;

         for C of Expression_String loop
            if C = '?' then
               if Index_Level = 0 then
                  raise Constraint_Error with "Index placeholders may only be used within an array context.";
               end if;

               Question_Run_Length := @ + 1;
            else
               Flush_Question_Run;
               Result.Append (VSS.Strings.Conversions.To_Virtual_String (String'(1 => C)));
            end if;
         end loop;

         Flush_Question_Run;
         return Result;
      end Expand_Index_Level;

      procedure Emit_Config_Map
        (Text               : Virtual_String;
         Location           : String  := GNAT.Source_Info.Source_Location;
         Trailing_Line_Feed : Boolean := True) is
      begin
         Config_Map_Out.Append (Text);
         Config_Map_Out.Append (" --  " & Conversions.To_Virtual_String (Location));
         if Trailing_Line_Feed then
            Config_Map_Out.Append (VSS.Characters.Latin.Line_Feed);
         end if;
      end Emit_Config_Map;

      procedure Emit_Reader
        (Text               : Virtual_String;
         Location           : String  := GNAT.Source_Info.Source_Location;
         Trailing_Line_Feed : Boolean := True) is
      begin
         Reader_Out.Append (Text);
         Reader_Out.Append (" --  " & Conversions.To_Virtual_String (Location));
         if Trailing_Line_Feed then
            Reader_Out.Append (VSS.Characters.Latin.Line_Feed);
         end if;
      end Emit_Reader;

      procedure Emit_Setter
        (Text               : Virtual_String;
         Location           : String  := GNAT.Source_Info.Source_Location;
         Trailing_Line_Feed : Boolean := True) is
      begin
         Setter_Out.Append (Text);
         Setter_Out.Append (" --  " & Conversions.To_Virtual_String (Location));
         if Trailing_Line_Feed then
            Setter_Out.Append (VSS.Characters.Latin.Line_Feed);
         end if;
      end Emit_Setter;

      function Path_To_Vector_Access_String (Path : String_Vectors.Vector) return Virtual_String is
         Result : Virtual_String := "";
      begin
         for I in Path.First_Index .. Path.Last_Index loop
            if I > Path.First_Index then
               Result := Result & ", ";
            end if;
            Result := Result & """" & Path (I) & """";
         end loop;

         return Result;
      end Path_To_Vector_Access_String;

      function Path_To_Vector_Access_String
        (Path : Config_Types.String_Vectors.Vector) return Virtual_String
      is
         Result : Virtual_String := "";
      begin
         for I in Path.First_Index .. Path.Last_Index loop
            if I > Path.First_Index then
               Result := Result & ", ";
            end if;
            Result := Result & """" & Path (I) & """";
         end loop;

         return Result;
      end Path_To_Vector_Access_String;

      function Dynamic_Presentation_Association (Outer : Component_Data) return Virtual_String is
      begin
         if Outer.Dynamic_Present_When_Path.Is_Empty then
            return ", Present_When => Prunt.Config.No_Presentation_Condition";
         else
            return
              ", Present_When => (Controller_Tag => "
              & Outer.Dynamic_Present_When_Tag
              & ", Controller_Path => "
              & Outer.Dynamic_Present_When_Path
              & ", Values => ["
              & Path_To_Vector_Access_String (Outer.Dynamic_Present_When_Values)
              & "])";
         end if;
      end Dynamic_Presentation_Association;

      function Effective_Schema_Default (Outer : Component_Data; Fallback : Virtual_String) return Virtual_String is
      begin
         if Outer.Schema_Default_Expr /= "" then
            return Outer.Schema_Default_Expr;
         else
            return Fallback;
         end if;
      end Effective_Schema_Default;

      function Effective_Display_Unit (Inner, Outer : Unit_Data) return Virtual_String is
      begin
         if Inner.Display /= "" then
            return Inner.Display;
         else
            return Outer.Display;
         end if;
      end Effective_Display_Unit;

      function Enum_Literal_Test
        (Enum_Type_Name : Virtual_String; Iterator_Name : Virtual_String; Literal_Name : Virtual_String)
         return Virtual_String
      is
      begin
         return
           Iterator_Name
           & " = "
           & Enum_Type_Name
           & "'Value ("""
           & Literal_Name
           & """)";
      end Enum_Literal_Test;

      function Enum_Literal_Present_When
        (Enum_Val       : Enum_Data;
         Enum_Type_Name : Virtual_String;
         Iterator_Name  : Virtual_String) return Virtual_String
      is
         Result   : Virtual_String := "";
         Is_First : Boolean        := True;
      begin
         if Enum_Val.Present_When.Is_Empty then
            return "True";
         end if;

         Result.Append ("(if ");
         for Cond in Enum_Val.Present_When.Iterate loop
            if not Is_First then
               Result.Append (" elsif ");
            end if;

            Result.Append
              (Enum_Literal_Test (Enum_Type_Name, Iterator_Name, Virtual_String_Maps.Key (Cond))
               & " then "
               & Virtual_String_Maps.Element (Cond));
            Is_First := False;
         end loop;
         Result.Append (" else True)");
         return Result;
      end Enum_Literal_Present_When;

      function Variant_Case_Present_When
        (Record_Val : Record_Data; Variant_Name : Virtual_String) return Virtual_String
      is
      begin
         if Global_Config.Contains (Record_Val.Discriminant_Type)
           and then Global_Config (Record_Val.Discriminant_Type).Kind = Enum_Kind
           and then
             Global_Config (Record_Val.Discriminant_Type).Enum_Value.Present_When.Contains (Variant_Name)
         then
            return Global_Config (Record_Val.Discriminant_Type).Enum_Value.Present_When (Variant_Name);
         else
            return "";
         end if;
      end Variant_Case_Present_When;

      procedure Handle_Item
        (Item          : Config_Type;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Prefix    : Virtual_String);

      procedure Handle_Boolean
        (Boolean_Val   : Boolean_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Expr      : Virtual_String)
      is
         pragma Unreferenced (Boolean_Val);
         Path_Str : constant Virtual_String := Path_To_Vector_Access_String (Path);
      begin
         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_Boolean'(Description => """
            & Outer.Description
            & """, Default => "
            & Effective_Schema_Default (Outer, Outer.Default)
            & Dynamic_Presentation_Association (Outer)
            & ")");
         Emit_Reader
           (Reader_Prefix
            & " := Boolean'(Data.Get(Prunt.Config.Config_Data_Paths.Vector'["
            & Path_Str
            & "]));");
         Emit_Setter ("Data.Set (Prunt.Config.Config_Data_Paths.Vector'[" & Path_Str & "], " & Ada_Expr & ");");
      end Handle_Boolean;

      procedure Handle_String
        (String_Val    : String_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Expr      : Virtual_String)
      is
         pragma Unreferenced (String_Val);
         Path_Str : constant Virtual_String := Path_To_Vector_Access_String (Path);
      begin
         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_String'(Description => """
            & Outer.Description
            & """, Default => "
            & Effective_Schema_Default (Outer, Outer.Default)
            & Dynamic_Presentation_Association (Outer)
            & ")");
         Emit_Reader
           (Reader_Prefix
            & " := Data.Get (Prunt.Config.Config_Data_Paths.Vector'["
            & Path_Str
            & "]);");
         Emit_Setter ("Data.Set (Prunt.Config.Config_Data_Paths.Vector'[" & Path_Str & "], " & Ada_Expr & ");");
      end Handle_String;

      procedure Handle_Float
        (Float_Val     : Float_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Expr      : Virtual_String)
      is
         Path_Str : constant Virtual_String := Path_To_Vector_Access_String (Path);
         Min_Expr : constant Virtual_String := Expand_Index_Level (Outer.Min);
         Max_Expr : constant Virtual_String := Expand_Index_Level (Outer.Max);
      begin
         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_Float'(Description => """
            & Outer.Description
            & """, Default => ("
            & Effective_Schema_Default (Outer, Outer.Default)
            & ")"
            & Virtual_String'
                (if Float_Val.Unit.Conversion /= "" then " / (" & Float_Val.Unit.Conversion & ")" else "")
            & ", Min => ("
            & Min_Expr
            & ")"
            & Virtual_String'
                (if Float_Val.Unit.Conversion /= "" then " / (" & Float_Val.Unit.Conversion & ")" else "")
            & ", Max => ("
            & Max_Expr
            & ")"
            & Virtual_String'
                (if Float_Val.Unit.Conversion /= "" then " / (" & Float_Val.Unit.Conversion & ")" else "")
            & ", Unit => """
            & Effective_Display_Unit (Float_Val.Unit, Outer.Unit)
            & """"
            & Dynamic_Presentation_Association (Outer)
            & ")");
         Emit_Reader
           (Reader_Prefix
            & " := Data.Get(Prunt.Config.Config_Data_Paths.Vector'["
            & Path_Str
            & "])"
            & (if Float_Val.Unit.Conversion /= "" then " * (" & Float_Val.Unit.Conversion & ")" else "")
            & ";");
         Emit_Setter
           ("Data.Set (Prunt.Config.Config_Data_Paths.Vector'["
            & Path_Str
            & "], ("
            & Ada_Expr
            & ")"
            & (if Float_Val.Unit.Conversion /= "" then " / (" & Float_Val.Unit.Conversion & ")" else "")
            & ");");
      end Handle_Float;

      procedure Handle_Ratio
        (Ratio_Val     : Ratio_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Expr      : Virtual_String)
      is
         pragma Unreferenced (Ratio_Val);
         Path_Str : constant Virtual_String := Path_To_Vector_Access_String (Path);
         Min_Expr : constant Virtual_String := Expand_Index_Level (Outer.Min);
         Max_Expr : constant Virtual_String := Expand_Index_Level (Outer.Max);
      begin
         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_Float_Ratio'(Description => """
            & Outer.Description
            & """, Default => "
            & Effective_Schema_Default (Outer, Outer.Default)
            & ", Min => "
            & Min_Expr
            & ", Max => "
            & Max_Expr
            & Dynamic_Presentation_Association (Outer)
            & ")");
         Emit_Reader (Reader_Prefix & " := Data.Get (Prunt.Config.Config_Data_Paths.Vector'[" & Path_Str & "]);");
         Emit_Setter ("Data.Set (Prunt.Config.Config_Data_Paths.Vector'[" & Path_Str & "], " & Ada_Expr & ");");
      end Handle_Ratio;

      procedure Handle_Integer
        (Integer_Val   : Integer_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Expr      : Virtual_String)
      is
         Path_Str : constant Virtual_String := Path_To_Vector_Access_String (Path);
         Min_Expr : constant Virtual_String := Expand_Index_Level (Outer.Min);
         Max_Expr : constant Virtual_String := Expand_Index_Level (Outer.Max);
      begin
         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_Integer'(Description => """
            & Outer.Description
            & """, Default => "
            & Effective_Schema_Default (Outer, Outer.Default)
            & Virtual_String'(if Integer_Val.Unit.Conversion /= "" then " / " else "")
            & Integer_Val.Unit.Conversion
            & ", Min => "
            & Min_Expr
            & (if Integer_Val.Unit.Conversion = "" then "" else " / " & Integer_Val.Unit.Conversion)
            & ", Max => "
            & Max_Expr
            & (if Integer_Val.Unit.Conversion = "" then "" else " / " & Integer_Val.Unit.Conversion)
            & ", Unit => """
            & Effective_Display_Unit (Integer_Val.Unit, Outer.Unit)
            & """"
            & Dynamic_Presentation_Association (Outer)
            & ")");
         Emit_Reader
           (Reader_Prefix
            & " := "
            & Outer.Type_Name
            & "(Long_Long_Integer'(Data.Get (Prunt.Config.Config_Data_Paths.Vector'["
            & Path_Str
            & "])));");
         Emit_Setter
           ("Data.Set (Prunt.Config.Config_Data_Paths.Vector'["
            & Path_Str
            & "], Long_Long_Integer ("
            & Ada_Expr
            & (if Integer_Val.Unit.Conversion /= "" then " / " & Integer_Val.Unit.Conversion else "")
            & "));");
      end Handle_Integer;

      procedure Handle_Component
        (Field         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Expr      : Virtual_String) is
         Present_When : constant Virtual_String := Expand_Index_Level (Field.Present_When);
      begin
         if not Global_Config.Contains (Field.Type_Name) then
            raise Constraint_Error with "Unknown type: " & Field.Type_Name'Image;
         end if;

         if Present_When /= "" then
            Emit_Reader ("if " & Present_When & " then");
            Emit_Setter ("if " & Present_When & " then");
         end if;

         Handle_Item (Global_Config (Field.Type_Name), Field, Path, Reader_Prefix, Ada_Expr);

         if Present_When /= "" then
            Emit_Reader ("end if;");
            Emit_Setter ("end if;");
         end if;
      end Handle_Component;

      procedure Handle_Enum
        (Enum_Val      : Enum_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Expr      : Virtual_String)
      is
         Path_Str : constant Virtual_String := Path_To_Vector_Access_String (Path);
         Options  : constant Virtual_String :=
           (if Outer.Options_Expr /= ""
            then Outer.Options_Expr
            else
              "[for I in "
              & Outer.Type_Name
              & " when "
              & Enum_Literal_Present_When (Enum_Val, Outer.Type_Name, "I")
              & " => +I'Image]");
      begin
         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_Discrete'(Description => """
            & Outer.Description
            & """, Default => "
            & Effective_Schema_Default (Outer, "+" & Outer.Default & "'Image")
            & ", Options => "
            & Options
            & Dynamic_Presentation_Association (Outer)
            & ")");
         Emit_Reader
           (Reader_Prefix
            & " := "
            & Outer.Type_Name
            & "'Value (VSS.Strings.Conversions.To_UTF_8_String (Data.Get (Prunt.Config.Config_Data_Paths.Vector'["
            & Path_Str
            & "])));");
         Emit_Setter
           ("Data.Set (Prunt.Config.Config_Data_Paths.Vector'[" & Path_Str & "], +(" & Ada_Expr & "'Image));");
      end Handle_Enum;

      procedure Handle_Array
        (Array_Val     : Array_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Prefix    : Virtual_String)
      is
         Loop_Index           : constant Virtual_String :=
           "Index_" & Conversions.To_Virtual_String (Trim (Index_Level'Image, Both));
         Element_Present_When : Virtual_String;
      begin
         Index_Level := @ + 1;
         Element_Present_When := Expand_Index_Level (Array_Val.Present_When);

         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_Sequence'(Description => """
            & Outer.Description
            & """, Tabbed => "
            & Virtual_String'(if Array_Val.Tabbed then "True" else "False")
            & Dynamic_Presentation_Association (Outer)
            & ", Children => [for "
            & Loop_Index
            & " in "
            & Array_Val.Index_Type
            & (if Element_Present_When /= "" then " when " & Element_Present_When else "")
            & " use +"
            & Loop_Index
            & "'Image => ");

         Emit_Reader ("for " & Loop_Index & " in " & Array_Val.Index_Type & " loop");
         Emit_Setter ("for " & Loop_Index & " in " & Array_Val.Index_Type & " loop");

         if Element_Present_When /= "" then
            Emit_Reader ("if " & Element_Present_When & " then");
            Emit_Setter ("if " & Element_Present_When & " then");
         end if;

         Handle_Component
           ((Outer
             with delta
               Type_Name                      => Array_Val.Element_Type,
               Description                    => "",
               --  Avoid duplicated description with nested arrays.
               Default                        => Outer.Type_Name & "'" & Outer.Default & "(" & Loop_Index & ")",
               Min                            => Array_Val.Min,
               Max                            => Array_Val.Max,
               Dynamic_Present_When_Tag       => "",
               Dynamic_Present_When_Path      => "",
               Dynamic_Present_When_Values    => []),
            Path & [""" & (+" & Loop_Index & "'Image) & """],
            Reader_Prefix & " (" & Loop_Index & ")",
            Ada_Prefix & " (" & Loop_Index & ")");

         if Element_Present_When /= "" then
            Emit_Setter ("end if;");
            Emit_Reader ("end if;");
         end if;

         Emit_Setter ("end loop;");
         Emit_Reader ("end loop;");
         Emit_Config_Map ("])");

         Index_Level := @ - 1;
      end Handle_Array;

      procedure Handle_Record
        (Record_Val    : Record_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Prefix    : Virtual_String)
      is
         Fixed_Kind_Str    : Virtual_String;
         Fixed_Desc_Suffix : Virtual_String := "";

         function Has_Conditional_Components (Components : Component_Data_Maps.Map) return Boolean is
         begin
            for C in Components.Iterate loop
               if Component_Data_Maps.Element (C).Present_When /= "" then
                  return True;
               end if;
            end loop;

            return False;
         end Has_Conditional_Components;

         function Has_Conditional_Variant_Cases return Boolean is
         begin
            if not Record_Val.Has_Variant then
               return False;
            end if;

            for Variant_C in Record_Val.Variants.Iterate loop
               if Variant_Case_Present_When (Record_Val, Variant_Case_Maps.Key (Variant_C)) /= "" then
                  return True;
               end if;
            end loop;

            return False;
         end Has_Conditional_Variant_Cases;

         function Needs_Others_Choice (Variant_C : Variant_Case_Maps.Cursor) return Boolean is
         begin
            return
              not Record_Val.Components.Is_Empty
              or else not Variant_Case_Maps.Element (Variant_C).Components.Is_Empty;
         end Needs_Others_Choice;

         function With_Containing_Default
           (Field : Component_Data; Name : Virtual_String) return Component_Data
         is
            Default_Text : constant String := Conversions.To_UTF_8_String (Outer.Default);
            Is_Name      : Boolean := Default_Text'Length > 0;
         begin
            for C of Default_Text loop
               if not (C in 'A' .. 'Z' | 'a' .. 'z' | '0' .. '9' | '_' | '.') then
                  Is_Name := False;
                  exit;
               end if;
            end loop;

            if not Is_Name then
               return Field;
            else
               return
                 (Field
                  with delta
                    Default => Outer.Default & "." & Name);
            end if;
         end With_Containing_Default;
         --  A containing record component can override the defaults declared by its type through a named constant.
         --  Reflect that constant in the generated child schema instead of reverting to the type-level defaults.

         procedure Emit_Component_Map
           (Components     : Component_Data_Maps.Map;
            Base_Path      : String_Vectors.Vector;
            Reader_Base    : Virtual_String;
            Ada_Base       : Virtual_String)
         is
            Is_First : Boolean := True;
         begin
            if Components.Is_Empty then
               Emit_Config_Map ("[]");
               return;
            end if;

            if not Has_Conditional_Components (Components) then
               Emit_Config_Map ("[");

               for C in Components.Iterate loop
                  declare
                     Name  : constant Virtual_String := Component_Data_Maps.Key (C);
                     Field : constant Component_Data :=
                       With_Containing_Default (Component_Data_Maps.Element (C), Name);
                  begin
                     if not Is_First then
                        Emit_Config_Map (", ");
                     end if;

                     Emit_Config_Map ("""" & Name & """ =>");
                     Handle_Component (Field, Base_Path & [Name], Reader_Base & "." & Name, Ada_Base & "." & Name);
                     Is_First := False;
                  end;
               end loop;

               Emit_Config_Map ("]");
            else
               for C in Components.Iterate loop
                  declare
                     Name  : constant Virtual_String := Component_Data_Maps.Key (C);
                     Field : constant Component_Data :=
                       With_Containing_Default (Component_Data_Maps.Element (C), Name);
                     Present_When : constant Virtual_String := Expand_Index_Level (Field.Present_When);
                  begin
                     if not Is_First then
                        Emit_Config_Map (" & ");
                     end if;

                     if Present_When /= "" then
                        Emit_Config_Map ("(if " & Present_When & " then ");
                     end if;

                     Emit_Config_Map ("[""" & Name & """ =>");
                     Handle_Component (Field, Base_Path & [Name], Reader_Base & "." & Name, Ada_Base & "." & Name);
                     Emit_Config_Map ("]");

                     if Present_When /= "" then
                        Emit_Config_Map (" else [])");
                     end if;

                     Is_First := False;
                  end;
               end loop;
            end if;
         end Emit_Component_Map;
      begin
         if Outer.Fixed_Kind /= "" then
            Fixed_Kind_Str := Expand_Index_Level (Outer.Fixed_Kind);

            if Record_Val.Has_Variant then
               declare
                  Is_First : Boolean := True;
               begin
                  Fixed_Desc_Suffix.Append (" & (if ");
                  for Variant_C in Record_Val.Variants.Iterate loop
                     if not Is_First then
                        Fixed_Desc_Suffix.Append (" elsif ");
                     end if;
                     Fixed_Desc_Suffix.Append (Fixed_Kind_Str & " = " & Variant_Case_Maps.Key (Variant_C));
                     Fixed_Desc_Suffix.Append
                       (" then (VSS.Characters.Latin.Line_Feed & (+"""
                        & Variant_Case_Maps.Element (Variant_C).Description
                        & """))");
                     Is_First := False;
                  end loop;

                  if not Is_First then
                     Fixed_Desc_Suffix.Append (" else +"""")");
                  else
                     Fixed_Desc_Suffix := "";
                  end if;
               end;
            end if;
         end if;

         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_Sequence'(Tabbed => "
            & Virtual_String'(if Record_Val.Tabbed then "True" else "False")
            & ", Description => """
            & Record_Val.Description
            & """"
            & Fixed_Desc_Suffix
            & Dynamic_Presentation_Association (Outer)
            & ", Children => Prunt.Config.Config_Property_Maps.""&"" (");
         --  Call `&` as a regular function so we can swap the arguments and place the variant part after the
         --  non-variant part. We can not simply place the variant code after the non-variant code generation as we use
         --  a delta aggregate to set the non-variant fields and delta aggregates can not set discriminants, which the
         --  variant code does.

         if Outer.Fixed_Kind /= "" then
            declare
               Is_First : Boolean := True;
            begin
               Emit_Config_Map ("Right => (");

               for Variant_C in Record_Val.Variants.Iterate loop
                  Emit_Config_Map
                    (Virtual_String'(if Is_First then "" else "els")
                     & "if "
                     & Fixed_Kind_Str
                     & " = "
                     & Variant_Case_Maps.Key (Variant_C)
                     & " then ");
                  Emit_Reader
                    (Virtual_String'(if Is_First then "" else "els")
                     & "if "
                     & Fixed_Kind_Str
                     & " = "
                     & Variant_Case_Maps.Key (Variant_C)
                     & " then");
                  Emit_Reader
                    (Reader_Prefix
                     & " := ("
                     & Record_Val.Discriminant
                     & " => "
                     & Variant_Case_Maps.Key (Variant_C)
                     & Virtual_String'(if Needs_Others_Choice (Variant_C) then ", others => <>" else "")
                     & ");");
                  Emit_Setter
                    (Virtual_String'(if Is_First then "" else "els")
                     & "if "
                     & Ada_Prefix
                     & "."
                     & Record_Val.Discriminant
                     & " = "
                     & Variant_Case_Maps.Key (Variant_C)
                     & " then");

                  Emit_Setter ("null;");

                  Emit_Component_Map
                    (Variant_Case_Maps.Element (Variant_C).Components,
                     Path,
                     Reader_Prefix,
                     Ada_Prefix);

                  Is_First := False;
               end loop;

               Emit_Reader ("else");
               Emit_Reader ("raise Constraint_Error;");
               Emit_Reader ("end if;");
               Emit_Config_Map ("else raise Constraint_Error),");
               Emit_Setter ("else");
               Emit_Setter ("raise Constraint_Error;");
               Emit_Setter ("end if;");
            end;
         elsif Record_Val.Has_Variant then
            declare
               Is_First : Boolean := True;
            begin
               Emit_Config_Map
                 ("Right => ["""
                  & Record_Val.Discriminant
                  & """ => Prunt.Config.Config_Property_Parameters_Variant'(Default => """
                  & Record_Val.Discriminant_Default
                  & """, Description => """", Present_When => Prunt.Config.No_Presentation_Condition, Children => ");
               --  Call `&` as a regular function so we can swap the arguments and place the variant part after the
               --  non-variant part. We can not simply place this code after the non-variant code generation as we use
               --  a delta aggregate to set the non-variant fields and delta aggregates can not set discriminants,
               --  which this code does.

               if not Has_Conditional_Variant_Cases then
                  Emit_Config_Map ("[");

                  for Variant_C in Record_Val.Variants.Iterate loop
                     declare
                        Name : constant Virtual_String := Variant_Case_Maps.Key (Variant_C);
                     begin
                        if not Is_First then
                           Emit_Config_Map (", ");
                        end if;

                        Emit_Config_Map
                          (""""
                           & Name
                           & """ => Prunt.Config.Config_Property_Parameters_Sequence'(Tabbed => "
                           & Virtual_String'(if Record_Val.Tabbed then "True" else "False")
                           & ", Description => """
                           & Variant_Case_Maps.Element (Variant_C).Description
                           & """, Present_When => Prunt.Config.No_Presentation_Condition, Children => ");
                        Emit_Reader
                          (Virtual_String'(if Is_First then "" else "els")
                           & "if Data.Get (Prunt.Config.Config_Data_Paths.Vector'["
                           & Path_To_Vector_Access_String (Path & [Record_Val.Discriminant, "Selected"])
                           & "]) = """
                           & Name
                           & """ then "
                           & Reader_Prefix
                           & " := ("
                           & Record_Val.Discriminant
                           & " => "
                           & Name
                           & Virtual_String'(if Needs_Others_Choice (Variant_C) then ", others => <>" else "")
                           & ");");
                        Emit_Setter
                          (Virtual_String'(if Is_First then "" else "els")
                           & "if "
                           & Ada_Prefix
                           & "."
                           & Record_Val.Discriminant
                           & " = "
                           & Name
                           & " then");

                        Emit_Setter ("null;");

                        Emit_Component_Map
                          (Variant_Case_Maps.Element (Variant_C).Components,
                           Path & [Record_Val.Discriminant, "Children", Name],
                           Reader_Prefix,
                           Ada_Prefix);

                        Emit_Config_Map (")");
                        Is_First := False;
                     end;
                  end loop;

                  Emit_Config_Map ("]");
               else
                  for Variant_C in Record_Val.Variants.Iterate loop
                     declare
                        Name      : constant Virtual_String := Variant_Case_Maps.Key (Variant_C);
                        Condition : constant Virtual_String := Variant_Case_Present_When (Record_Val, Name);
                     begin
                        Emit_Config_Map (Virtual_String'(if Is_First then "" else " & "));
                        if Condition /= "" then
                           Emit_Config_Map ("(if " & Condition & " then ");
                        end if;

                        Emit_Config_Map
                          ("["""
                           & Name
                           & """ => Prunt.Config.Config_Property_Parameters_Sequence'(Tabbed => "
                           & Virtual_String'(if Record_Val.Tabbed then "True" else "False")
                           & ", Description => """
                           & Variant_Case_Maps.Element (Variant_C).Description
                           & """, Present_When => Prunt.Config.No_Presentation_Condition, Children => ");
                        Emit_Reader
                          (Virtual_String'(if Is_First then "" else "els")
                           & "if Data.Get (Prunt.Config.Config_Data_Paths.Vector'["
                           & Path_To_Vector_Access_String (Path & [Record_Val.Discriminant, "Selected"])
                           & "]) = """
                           & Name
                           & """ then "
                           & Reader_Prefix
                           & " := ("
                           & Record_Val.Discriminant
                           & " => "
                           & Name
                           & Virtual_String'(if Needs_Others_Choice (Variant_C) then ", others => <>" else "")
                           & ");");
                        Emit_Setter
                          (Virtual_String'(if Is_First then "" else "els")
                           & "if "
                           & Ada_Prefix
                           & "."
                           & Record_Val.Discriminant
                           & " = "
                           & Name
                           & " then");

                        Emit_Setter ("null;");

                        Emit_Component_Map
                          (Variant_Case_Maps.Element (Variant_C).Components,
                           Path & [Record_Val.Discriminant, "Children", Name],
                           Reader_Prefix,
                           Ada_Prefix);

                        Emit_Config_Map (")]");
                        if Condition /= "" then
                           Emit_Config_Map (" else [])");
                        end if;

                        Is_First := False;
                     end;
                  end loop;
               end if;

               Emit_Reader ("else");
               Emit_Reader ("raise Constraint_Error;");
               Emit_Reader ("end if;");
               Emit_Config_Map (")],");
               Emit_Setter ("else");
               Emit_Setter ("raise Constraint_Error;");
               Emit_Setter ("end if;");
            end;
         else
            Emit_Config_Map ("Right => [],");
         end if;

         if Record_Val.Components.Is_Empty and then not Record_Val.Has_Variant then
            Emit_Setter ("null;");
         end if;

         Emit_Config_Map ("Left => ");
         Emit_Component_Map (Record_Val.Components, Path, Reader_Prefix, Ada_Prefix);
         Emit_Config_Map ("))");
      end Handle_Record;

      procedure Handle_Item
        (Item          : Config_Type;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Prefix    : Virtual_String) is
      begin
         case Item.Kind is
            when Record_Kind  =>
               Handle_Record (Item.Record_Value, Outer, Path, Reader_Prefix, Ada_Prefix);

            when Array_Kind   =>
               Handle_Array (Item.Array_Value, Outer, Path, Reader_Prefix, Ada_Prefix);

            when Enum_Kind    =>
               Handle_Enum (Item.Enum_Value, Outer, Path, Reader_Prefix, Ada_Prefix);

            when Boolean_Kind =>
               Handle_Boolean (Item.Boolean_Value, Outer, Path, Reader_Prefix, Ada_Prefix);

            when String_Kind  =>
               Handle_String (Item.String_Value, Outer, Path, Reader_Prefix, Ada_Prefix);

            when Integer_Kind =>
               Handle_Integer (Item.Integer_Value, Outer, Path, Reader_Prefix, Ada_Prefix);

            when Float_Kind   =>
               Handle_Float (Item.Float_Value, Outer, Path, Reader_Prefix, Ada_Prefix);

            when Ratio_Kind   =>
               Handle_Ratio (Item.Ratio_Value, Outer, Path, Reader_Prefix, Ada_Prefix);
         end case;
      end Handle_Item;

      procedure Append_Line (Target : in out Virtual_String; Text : Virtual_String) is
      begin
         Target.Append (Text);
         Target.Append (VSS.Characters.Latin.Line_Feed);
      end Append_Line;

      function New_Path_Node return Virtual_String is
      begin
         Path_Node_Count := @ + 1;
         return "Path_Node_" & Conversions.To_Virtual_String (Trim (Path_Node_Count'Image, Both));
      end New_Path_Node;

      procedure Declare_Path_Node (Name : Virtual_String) is
      begin
         Append_Line (Path_Type_Declarations, "type " & Name & " is private;");
         Append_Line
           (Path_Private_Declarations,
            "type " & Name & " is record Value : Standard.Prunt.Config.Config_Path; end record;");
         Append_Line
           (Path_Subprogram_Declarations,
            "function Path (Self : " & Name & ") return Standard.Prunt.Config.Config_Path;");
         Append_Line
           (Path_Subprogram_Bodies,
            "function Path (Self : " & Name & ") return Standard.Prunt.Config.Config_Path is (Self.Value);");
      end Declare_Path_Node;

      procedure Generate_Path_Record
        (Item : Config_Type; Outer : Component_Data; Node_Name : Virtual_String);

      procedure Emit_Path_Selector
        (Parent_Node    : Virtual_String;
         Selector_Name : Virtual_String;
         Target_Item   : Config_Type;
         Target_Outer  : Component_Data;
         Parameters    : Virtual_String;
         Suffix        : Virtual_String;
         Selection     : Virtual_String := "";
         Selected      : Virtual_String := "")
      is
         Return_Type : Virtual_String := "Standard.Prunt.Config.Config_Path";
         Builder     : Virtual_String;
      begin
         if Target_Item.Kind = Record_Kind then
            Return_Type := New_Path_Node;
            Declare_Path_Node (Return_Type);
            Generate_Path_Record (Target_Item, Target_Outer, Return_Type);
         end if;

         Append_Line
           (Path_Subprogram_Declarations,
            "function "
            & Selector_Name
            & " (Self : "
            & Parent_Node
            & Parameters
            & ") return "
            & Return_Type
            & ";");

         if Selection = "" then
            Builder := "Standard.Prunt.Config.Paths.Append (Self.Value, " & Suffix & ")";
         else
            Builder :=
              "Standard.Prunt.Config.Paths.Append_Selected (Self.Value, "
              & Suffix
              & ", "
              & Selection
              & ", +"""
              & Selected
              & """)";
         end if;

         if Target_Item.Kind = Record_Kind then
            Builder := "(Value => " & Builder & ")";
         end if;

         Append_Line
           (Path_Subprogram_Bodies,
            "function "
            & Selector_Name
            & " (Self : "
            & Parent_Node
            & Parameters
            & ") return "
            & Return_Type
            & " is ("
            & Builder
            & ");");
      end Emit_Path_Selector;

      procedure Emit_Path_Component
        (Parent_Node    : Virtual_String;
         Selector_Name : Virtual_String;
         Component     : Component_Data;
         Suffix        : Virtual_String;
         Selection     : Virtual_String := "";
         Selected      : Virtual_String := "")
      is
         Item : constant Config_Type := Global_Config (Component.Type_Name);

         procedure Emit_Array
           (Array_Item  : Config_Type;
            Array_Outer : Component_Data;
            Parameters  : Virtual_String;
            Full_Suffix : Virtual_String;
            Depth       : Positive);

         procedure Emit_Array
           (Array_Item  : Config_Type;
            Array_Outer : Component_Data;
            Parameters  : Virtual_String;
            Full_Suffix : Virtual_String;
            Depth       : Positive)
         is
            Array_Val      : constant Array_Data := Array_Item.Array_Value;
            Index_Name     : constant Virtual_String :=
              "Index_" & Conversions.To_Virtual_String (Trim (Depth'Image, Both));
            New_Parameters : constant Virtual_String :=
              Parameters & "; " & Index_Name & " : " & Array_Val.Index_Type;
            New_Suffix     : constant Virtual_String :=
              Full_Suffix & " & [+" & Index_Name & "'Image]";
            Element_Outer  : constant Component_Data :=
              (Array_Outer with delta Type_Name => Array_Val.Element_Type, Description => "");
            Element_Item   : constant Config_Type := Global_Config (Array_Val.Element_Type);
         begin
            if Element_Item.Kind = Array_Kind then
               Emit_Array (Element_Item, Element_Outer, New_Parameters, New_Suffix, Depth + 1);
            else
               Emit_Path_Selector
                 (Parent_Node,
                  Selector_Name,
                  Element_Item,
                  Element_Outer,
                  New_Parameters,
                  New_Suffix,
                  Selection,
                  Selected);
            end if;
         end Emit_Array;
      begin
         if Item.Kind = Array_Kind then
            Path_Has_Arrays := True;
            Emit_Array (Item, Component, "", Suffix, 1);
         else
            Emit_Path_Selector
              (Parent_Node, Selector_Name, Item, Component, "", Suffix, Selection, Selected);
         end if;
      end Emit_Path_Component;

      procedure Generate_Path_Record
        (Item : Config_Type; Outer : Component_Data; Node_Name : Virtual_String)
      is
         Record_Val : constant Record_Data := Item.Record_Value;
      begin
         for C in Record_Val.Components.Iterate loop
            declare
               Name      : constant Virtual_String := Component_Data_Maps.Key (C);
               Component : constant Component_Data := Component_Data_Maps.Element (C);
            begin
               Emit_Path_Component (Node_Name, Name, Component, "[+""" & Name & """]");
            end;
         end loop;

         if Record_Val.Has_Variant then
            Emit_Path_Selector
              (Node_Name,
               Record_Val.Discriminant,
               (Kind => String_Kind, String_Value => (null record)),
               (others => <>),
               "",
               "[+""" & Record_Val.Discriminant & """]");

            for V in Record_Val.Variants.Iterate loop
               declare
                  Case_Name    : constant Virtual_String := Variant_Case_Maps.Key (V);
                  Variant_Data : constant Variant_Case_Data := Variant_Case_Maps.Element (V);
               begin
                  for C in Variant_Data.Components.Iterate loop
                     declare
                        Name      : constant Virtual_String := Component_Data_Maps.Key (C);
                        Component : constant Component_Data := Component_Data_Maps.Element (C);
                     begin
                        if Outer.Fixed_Kind = "" then
                           Emit_Path_Component
                             (Node_Name,
                              Name,
                              Component,
                              "[+"""
                              & Record_Val.Discriminant
                              & """, +""Children"", +"""
                              & Case_Name
                              & """, +"""
                              & Name
                              & """]",
                              "[+""" & Record_Val.Discriminant & """, +""Selected""]",
                              Case_Name);
                        else
                           Emit_Path_Component (Node_Name, Name, Component, "[+""" & Name & """]");
                        end if;
                     end;
                  end loop;
               end;
            end loop;
         end if;
      end Generate_Path_Record;

      procedure Generate_Config_Paths is
         Unit_Name : constant Virtual_String := Data.Name & ".Config_Paths";
         Root_Node : constant Virtual_String := New_Path_Node;
         Spec_Out, Body_Out : Virtual_String;
      begin
         Declare_Path_Node (Root_Node);
         Generate_Path_Record (Global_Config (Data.Root_Type), (others => <>), Root_Node);

         Append_Line (Spec_Out, "pragma Style_Checks (Off);");
         Append_Line
           (Spec_Out,
            "--  This file is automatically generated based on the contents of "
            & Conversions.To_Virtual_String (Filename));
         Append_Line (Spec_Out, "--  Run config_codegen to regenerate this file.");
         Append_Line (Spec_Out, "with Prunt.Config;");
         Append_Line (Spec_Out, "private with Prunt.Config.Paths;");
         Append_Line (Spec_Out, "private generic");
         Append_Line (Spec_Out, "package " & Unit_Name & " is");
         Spec_Out.Append (Path_Type_Declarations);
         Append_Line (Spec_Out, "Root : constant " & Root_Node & ";");
         Spec_Out.Append (Path_Subprogram_Declarations);
         Append_Line (Spec_Out, "private");
         Spec_Out.Append (Path_Private_Declarations);
         Append_Line
           (Spec_Out,
            "Root : constant "
            & Root_Node
            & " := (Value => Standard.Prunt.Config.Paths.Empty_Path);");
         Append_Line (Spec_Out, "end " & Unit_Name & ";");

         Append_Line (Body_Out, "pragma Style_Checks (Off);");
         Append_Line
           (Body_Out,
            "--  This file is automatically generated based on the contents of "
            & Conversions.To_Virtual_String (Filename));
         Append_Line (Body_Out, "--  Run config_codegen to regenerate this file.");
         Append_Line (Body_Out, "package body " & Unit_Name & " is");
         if Path_Has_Arrays then
            Append_Line (Body_Out, "use type Standard.Prunt.Config.Config_Data_Paths.Vector;");
         end if;
         Append_Line (Body_Out, "pragma Annotate (Xcov, Exempt_On, ""Generated config paths."");");
         Body_Out.Append (Path_Subprogram_Bodies);
         Append_Line (Body_Out, "pragma Annotate (Xcov, Exempt_Off);");
         Append_Line (Body_Out, "end " & Unit_Name & ";");

         Write_File
           (Ada.Directories.Compose
              (Containing_Directory => Out_Dir,
               Name                 => Ada.Directories.Base_Name (Filename) & "-config_paths.ads"),
            Spec_Out);
         Write_File
           (Ada.Directories.Compose
              (Containing_Directory => Out_Dir,
               Name                 => Ada.Directories.Base_Name (Filename) & "-config_paths.adb"),
            Body_Out);
      end Generate_Config_Paths;
   begin

      if not Ada.Directories.Exists (Out_Dir) then
         Ada.Directories.Create_Directory (Out_Dir);
      end if;

      if Data.Root_Type /= "" and then Data.Config.Contains (Data.Root_Type) then
         Emit_Config_Map ("pragma Style_Checks (Off);");
         Emit_Config_Map
           ("--  This file is automatically generated based on the contents of "
            & Conversions.To_Virtual_String (Filename));
         Emit_Config_Map ("--  Run config_codegen to regenerate this file.");
         Emit_Config_Map ("pragma Warnings (Off, ""no entities of * are referenced"");");
         Emit_Config_Map ("pragma Warnings (Off, ""unit * is not referenced"");");
         Emit_Config_Map ("with VSS.Characters.Latin;");
         Emit_Config_Map ("with Prunt.Config;");
         Emit_Config_Map ("pragma Warnings (On, ""unit * is not referenced"");");
         Emit_Config_Map ("pragma Warnings (On, ""no entities of * are referenced"");");
         Emit_Config_Map ("separate (" & Data.Name & ")");
         Emit_Config_Map ("function Build_Schema return Prunt.Config.Config_Property_Maps.Map is");
         Emit_Config_Map ("pragma Unsuppress (All_Checks);");
         Emit_Config_Map ("pragma Warnings (Off, ""use clause for private type * has no effect"");");
         Emit_Config_Map ("pragma Warnings (Off, ""use clause for type * has no effect"");");
         Emit_Config_Map ("use type Prunt.Config.Config_Property_Maps.Map;");
         Emit_Config_Map ("pragma Warnings (On, ""use clause for type * has no effect"");");
         Emit_Config_Map ("pragma Warnings (On, ""use clause for private type * has no effect"");");
         Emit_Config_Map ("begin");
         Emit_Config_Map ("pragma Annotate (Xcov, Exempt_On, ""Generated config schema."");");
         Emit_Config_Map ("pragma Extensions_Allowed (On);");
         Emit_Config_Map ("return");

         Emit_Reader ("pragma Style_Checks (Off);");
         Emit_Reader
           ("--  This file is automatically generated based on the contents of "
            & Conversions.To_Virtual_String (Filename));
         Emit_Reader ("--  Run config_codegen to regenerate this file.");
         Emit_Reader ("pragma Warnings (Off, ""no entities of * are referenced"");");
         Emit_Reader ("pragma Warnings (Off, ""unit * is not referenced"");");
         Emit_Reader ("with VSS.Characters.Latin;");
         Emit_Reader ("pragma Warnings (On, ""unit * is not referenced"");");
         Emit_Reader ("pragma Warnings (On, ""no entities of * are referenced"");");
         Emit_Reader ("separate (" & Data.Name & ")");
         Emit_Reader
           ("function Config_Data_To_User_Config (Data : Prunt.Config.Config_Data) return User_Config is");
         Emit_Reader ("pragma Unsuppress (All_Checks);");
         Emit_Reader ("begin");
         Emit_Reader ("pragma Annotate (Xcov, Exempt_On, ""Generated config conversion."");");
         Emit_Reader ("pragma Extensions_Allowed (On);");
         Emit_Reader ("return Result : User_Config do");

         Emit_Setter ("pragma Style_Checks (Off);");
         Emit_Setter
           ("--  This file is automatically generated based on the contents of "
            & Conversions.To_Virtual_String (Filename));
         Emit_Setter ("--  Run config_codegen to regenerate this file.");
         Emit_Setter ("pragma Warnings (Off, ""no entities of * are referenced"");");
         Emit_Setter ("pragma Warnings (Off, ""unit * is not referenced"");");
         Emit_Setter ("with VSS.Characters.Latin;");
         Emit_Setter ("pragma Warnings (On, ""unit * is not referenced"");");
         Emit_Setter ("pragma Warnings (On, ""no entities of * are referenced"");");
         Emit_Setter ("separate (" & Data.Name & ")");
         Emit_Setter
           ("procedure User_Config_To_Config_Data (Data : in out Prunt.Config.Config_Data; Config : User_Config) is");
         Emit_Setter ("pragma Unsuppress (All_Checks);");
         Emit_Setter ("pragma Extensions_Allowed (On);");
         Emit_Setter ("begin");
         Emit_Setter ("pragma Annotate (Xcov, Exempt_On, ""Generated config conversion."");");

         Handle_Item
           (Item          => Data.Config (Data.Root_Type),
            Outer         => (others => <>),
            Path          => [],
            Reader_Prefix => "Result",
            Ada_Prefix    => "Config");

         Emit_Setter ("pragma Annotate (Xcov, Exempt_Off);");
         Emit_Setter ("pragma Style_Checks (On);");
         Emit_Setter (Text => "end User_Config_To_Config_Data;", Trailing_Line_Feed => False);

         Emit_Reader ("end return;");
         Emit_Reader ("pragma Annotate (Xcov, Exempt_Off);");
         Emit_Reader ("pragma Style_Checks (On);");
         Emit_Reader (Text => "end Config_Data_To_User_Config;", Trailing_Line_Feed => False);

         Emit_Config_Map (".Children;");
         Emit_Config_Map ("pragma Annotate (Xcov, Exempt_Off);");
         Emit_Config_Map ("pragma Style_Checks (On);");
         Emit_Config_Map (Text => "end Build_Schema;", Trailing_Line_Feed => False);


         Write_File
           (Ada.Directories.Compose
              (Containing_Directory => Out_Dir, Name => Ada.Directories.Base_Name (Filename) & "-build_schema.adb"),
            Config_Map_Out);
         Write_File
           (Ada.Directories.Compose
              (Containing_Directory => Out_Dir,
               Name                 => Ada.Directories.Base_Name (Filename) & "-config_data_to_user_config.adb"),
            Reader_Out);
         Write_File
           (Ada.Directories.Compose
              (Containing_Directory => Out_Dir,
               Name                 => Ada.Directories.Base_Name (Filename) & "-user_config_to_config_data.adb"),
            Setter_Out);

         Generate_Config_Paths;
      end if;

      if not Data.Gcode_Commands.Is_Empty then
         Generate_Gcode_Dispatch (Filename, Data);
         Generate_Gcode_Commands_List (Filename, Data);
      end if;
   end Generate_Files;

end Config_Generator;
