--  Part of the Prunt Motion Controller
--
--  Copyright (C) 2026 Liam Powell (liam@prunt3d.com)
--
--  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
--  documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
--  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
--  permit persons to whom the Software is furnished to do so, subject to the following conditions:
--
--  The above copyright notice and this permission notice (including the next paragraph) shall be included in all
--  copies or substantial portions of the Software.
--
--  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
--  THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
--  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
--  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
--  SOFTWARE.
--------------------------------------------------

--  If you're reading this file then there's a good chance that you're wondering why the `Config_Data_To_User_Config`
--  functions are generating some convoluted nonsense with explicit statements instead of a nice, easy to generate
--  expression like everything else. The reason is that GNAT is broken and will generate bogus visibility errors when
--  using an aggregate expression to generate an array: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=124282

with Ada.Directories;
with Ada.Strings;       use Ada.Strings;
with Ada.Strings.Fixed; use Ada.Strings.Fixed;
with Ada.Text_IO;       use Ada.Text_IO;
with GNAT.Source_Info;
with VSS.Characters.Latin;
with VSS.String_Vectors;
with VSS.Strings.Conversions;

package body Config_Generator is

   pragma Extensions_Allowed (On);

   Out_Dir : constant String := "generated_src_modules";

   procedure Write_File (Filename : String; Content : Virtual_String) is
      File : Ada.Text_IO.File_Type;
   begin
      Put_Line ("Writing file: " & Filename);
      Create (File, Out_File, Filename);
      Put (File, Conversions.To_UTF_8_String (Content));
      Close (File);
   end Write_File;

   procedure Generate_Gcode_Dispatch (Filename : String; Data : Module_Data) is
      Letters         : String_Vectors.Vector;
      Current_Map_Out : Virtual_String;

      procedure Emit (Text : Virtual_String; Location : String := GNAT.Source_Info.Source_Location) is
      begin
         Current_Map_Out.Append (Text);
         Current_Map_Out.Append (" --  " & Conversions.To_Virtual_String (Location));
         Current_Map_Out.Append (VSS.Characters.Latin.Line_Feed);
      end Emit;

   begin
      Emit ("pragma Style_Checks (Off);");
      Emit
        ("--  This file is automatically generated based on the contents of "
         & Conversions.To_Virtual_String (Filename));
      Emit ("--  Run config_codegen to regenerate this file.");
      Emit ("pragma Warnings (Off, ""no entities of * are referenced"");");
      Emit ("pragma Warnings (Off, ""unit * is not referenced"");");
      Emit ("with Prunt.Gcode_Arguments;");
      Emit ("with VSS.Characters.Latin;");
      Emit ("pragma Warnings (On, ""unit * is not referenced"");");
      Emit ("pragma Warnings (On, ""no entities of * are referenced"");");
      Emit ("separate (" & Data.Name & ")");
      Emit
        ("procedure Gcode_Dispatch (This : in out Module_Instance; Args : in out Gcode_Arguments.Arguments; "
         & "Planner : Prunt.Module_Types.Planner_Interface'Class; "
         & "Command_Identifier : Prunt.Module_Types.Gcode_Command_Identifier) is");
      Emit ("pragma Unsuppress (All_Checks);");
      Emit ("use type Prunt.Gcode_Arguments.Argument_Kind;");
      Emit ("begin");
      Emit ("pragma Extensions_Allowed (On);");
      Emit ("case Command_Identifier.Argument is");

      for C in Data.Gcode_Commands.Iterate loop
         declare
            Key : constant Gcode_Key := Gcode_Command_Maps.Key (C);
         begin
            if not Letters.Contains (Key.Letter) then
               Letters.Append (Key.Letter);
            end if;
         end;
      end loop;

      for L of Letters loop
         Emit ("when '" & L & "' =>");
         Emit ("case Command_Identifier.Number is");

         declare
            Numbers : String_Vectors.Vector;
         begin
            for C in Data.Gcode_Commands.Iterate loop
               declare
                  Key     : constant Gcode_Key := Gcode_Command_Maps.Key (C);
                  Num_Str : constant Virtual_String := Conversions.To_Virtual_String (Trim (Key.Number'Image, Both));
               begin
                  if Key.Letter = L and then not Numbers.Contains (Num_Str) then
                     Numbers.Append (Num_Str);
                  end if;
               end;
            end loop;

            for N of Numbers loop
               Emit ("when " & N & " =>");

               declare
                  Variants : constant Config_Types.Gcode_Command_Vectors.Vector :=
                    Data.Gcode_Commands.Element
                      ((Letter => L, Number => Integer'Value (Conversions.To_UTF_8_String (N))));
               begin

                  declare
                     First_Var : Boolean := True;
                  begin
                     for Variant of Variants loop
                        declare
                           Conditions : Virtual_String;
                           First_Cond : Boolean := True;
                        begin
                           for Arg_C in Variant.Arguments.Iterate loop
                              declare
                                 Arg_Name : constant Virtual_String := Gcode_Argument_Maps.Key (Arg_C);
                                 Arg_Data : constant Gcode_Argument_Data := Gcode_Argument_Maps.Element (Arg_C);
                                 Checks   : Virtual_String;

                                 procedure Add_Check (K : Virtual_String) is
                                 begin
                                    if Checks /= "" then
                                       Checks.Append (" or else ");
                                    end if;
                                    Checks.Append ("Args.Kind ('" & Arg_Name & "') = " & K);
                                 end Add_Check;
                              begin
                                 if Arg_Name /= "This" and then Arg_Name /= "Planner" then
                                    if Arg_Data.Arg_Kinds (Config_Types.Integer_Kind) then
                                       Add_Check ("Gcode_Arguments.Integer_Kind");
                                    end if;
                                    if Arg_Data.Arg_Kinds (Config_Types.Float_Kind) then
                                       Add_Check ("Gcode_Arguments.Float_Kind");
                                    end if;
                                    if Arg_Data.Arg_Kinds (Config_Types.String_Kind) then
                                       Add_Check ("Gcode_Arguments.String_Kind");
                                    end if;
                                    if Arg_Data.Arg_Kinds (Config_Types.Not_Present_Kind) then
                                       Add_Check ("Gcode_Arguments.Non_Existent_Kind");
                                    end if;
                                    if Arg_Data.Arg_Kinds (Config_Types.No_Value_Kind) then
                                       Add_Check ("Gcode_Arguments.No_Value_Kind");
                                    end if;

                                    if Checks /= "" then
                                       if not First_Cond then
                                          Conditions.Append (" and then ");
                                       end if;
                                       Conditions.Append ("(" & Checks & ")");
                                       First_Cond := False;
                                    end if;
                                 end if;
                              end;
                           end loop;

                           if Conditions = "" then
                              Conditions := "Standard.True";
                           end if;

                           Emit (Virtual_String'(if First_Var then "" else "els") & "if " & Conditions & " then");

                           declare
                              Args_Call : Virtual_String;
                              First_Arg : Boolean := True;
                           begin
                              for Arg_C in
                                Variant.Arguments.Iterate
                                when Gcode_Argument_Maps.Key (Arg_C) /= "This"
                                and then Gcode_Argument_Maps.Key (Arg_C) /= "Planner"
                              loop
                                 declare
                                    Arg_Name     : constant Virtual_String := Gcode_Argument_Maps.Key (Arg_C);
                                    Arg_Data     : constant Gcode_Argument_Data := Gcode_Argument_Maps.Element (Arg_C);
                                    Type_Name_St : constant String := Conversions.To_UTF_8_String (Arg_Data.Type_Name);
                                    Val_Expr     : Virtual_String;
                                 begin
                                    if not First_Arg then
                                       Args_Call.Append (", ");
                                    end if;

                                    if Index (Type_Name_St, "Optional_Float") > 0 then
                                       Val_Expr :=
                                         "(if Args.Kind ('"
                                         & Arg_Name
                                         & "') /= Gcode_Arguments.Non_Existent_Kind then "
                                         & "(Present => True, Value => Args.Consume_Float ('"
                                         & Arg_Name
                                         & "')) else (Present => False))";
                                       if Arg_Data.Default /= "" then
                                          raise Constraint_Error
                                            with
                                              "Optional_Float can not have default ("
                                              & L'Image
                                              & N'Image
                                              & ": "
                                              & Variant'Image
                                              & ")";
                                       end if;
                                    elsif Index (Type_Name_St, "Optional_Integer") > 0 then
                                       Val_Expr :=
                                         "(if Args.Kind ('"
                                         & Arg_Name
                                         & "') /= Gcode_Arguments.Non_Existent_Kind then "
                                         & "(Present => True, Value => Args.Consume_Integer ('"
                                         & Arg_Name
                                         & "')) else (Present => False))";
                                       if Arg_Data.Default /= "" then
                                          raise Constraint_Error
                                            with
                                              "Optional_Integer can not have default ("
                                              & L'Image
                                              & N'Image
                                              & ": "
                                              & Variant'Image
                                              & ")";
                                       end if;
                                    elsif Index (Type_Name_St, "Optional_String") > 0 then
                                       Val_Expr :=
                                         "(if Args.Kind ('"
                                         & Arg_Name
                                         & "') /= Gcode_Arguments.Non_Existent_Kind then "
                                         & "(Present => True, Value => Args.Consume_String ('"
                                         & Arg_Name
                                         & "')) else (Present => False))";
                                       if Arg_Data.Default /= "" then
                                          raise Constraint_Error
                                            with
                                              "Optional_String can not have default ("
                                              & L'Image
                                              & N'Image
                                              & ": "
                                              & Variant'Image
                                              & ")";
                                       end if;
                                    elsif Index (Type_Name_St, "Optional_No_Value") > 0 then
                                       Val_Expr :=
                                         "(Present => Args.Consume_No_Value_Or_False ('" & Arg_Name & "'))";
                                       if Arg_Data.Default /= "" then
                                          raise Constraint_Error
                                            with
                                              "Optional_No_Value can not have default ("
                                              & L'Image
                                              & N'Image
                                              & ": "
                                              & Variant'Image
                                              & ")";
                                       end if;
                                    elsif Index (Type_Name_St, "No_Value") > 0 then
                                       Val_Expr :=
                                         "(if Args.Consume_No_Value ('"
                                         & Arg_Name
                                         & "') then (null record) else (null record))";
                                       if Arg_Data.Default /= "" then
                                          raise Constraint_Error
                                            with
                                              "No_Value can not have default ("
                                              & L'Image
                                              & N'Image
                                              & ": "
                                              & Variant'Image
                                              & ")";
                                       end if;
                                    elsif Index (Type_Name_St, "Dimensionless") > 0 then
                                       if Arg_Data.Default /= "" then
                                          Val_Expr :=
                                            "Args.Consume_Float_Or_Default ('"
                                            & Arg_Name
                                            & "', "
                                            & Arg_Data.Default
                                            & ")";
                                       else
                                          Val_Expr := "Args.Consume_Float ('" & Arg_Name & "')";
                                       end if;
                                    elsif Index (Type_Name_St, "Argument_Integer") > 0 then
                                       if Arg_Data.Default /= "" then
                                          Val_Expr :=
                                            "Args.Consume_Integer_Or_Default ('"
                                            & Arg_Name
                                            & "', "
                                            & Arg_Data.Default
                                            & ")";
                                       else
                                          Val_Expr := "Args.Consume_Integer ('" & Arg_Name & "')";
                                       end if;
                                    elsif Index (Type_Name_St, "String") > 0 then
                                       if Arg_Data.Default /= "" then
                                          Val_Expr :=
                                            "Args.Consume_String_Or_Default ('"
                                            & Arg_Name
                                            & "', "
                                            & Arg_Data.Default
                                            & ")";
                                       else
                                          Val_Expr := "Args.Consume_String ('" & Arg_Name & "')";
                                       end if;
                                    else
                                       raise Constraint_Error
                                         with
                                           "Unhandled argument type ("
                                           & L'Image
                                           & N'Image
                                           & ": "
                                           & Variant'Image
                                           & ")";
                                    end if;

                                    Args_Call.Append (Arg_Name & " => " & Val_Expr);
                                    First_Arg := False;
                                 end;
                              end loop;

                              if not First_Arg then
                                 Args_Call := ", " & Args_Call;
                              end if;

                              Emit
                                ("This."
                                 & Variant.Name
                                 & " (Planner => Planner"
                                 & Args_Call
                                 & ");");
                           end;

                           First_Var := False;
                        end;
                     end loop;
                     Emit ("else");
                     Emit ("raise Constraint_Error with ""No matching G-code variant found."";");
                     Emit ("end if;");
                  end;
               end;
            end loop;

            Emit ("when others =>");
            Emit ("raise Constraint_Error with ""Unknown G-code command."";");
         end;
         Emit ("end case;");
      end loop;

      Emit ("when others =>");
      Emit ("raise Constraint_Error with ""Unknown G-code command identifier."";");
      Emit ("end case;");
      Emit ("end Gcode_Dispatch;");

      Write_File
        (Ada.Directories.Compose
           (Containing_Directory => Out_Dir, Name => Ada.Directories.Base_Name (Filename) & "-gcode_dispatch.adb"),
         Current_Map_Out);
   end Generate_Gcode_Dispatch;

   procedure Generate_Gcode_Commands_List (Filename : String; Data : Module_Data) is
      Current_Map_Out : Virtual_String;

      procedure Emit (Text : Virtual_String; Location : String := GNAT.Source_Info.Source_Location) is
      begin
         Current_Map_Out.Append (Text);
         Current_Map_Out.Append (" --  " & Conversions.To_Virtual_String (Location));
         Current_Map_Out.Append (VSS.Characters.Latin.Line_Feed);
      end Emit;
   begin
      Emit ("pragma Style_Checks (Off);");
      Emit
        ("--  This file is automatically generated based on the contents of "
         & Conversions.To_Virtual_String (Filename));
      Emit ("--  Run config_codegen to regenerate this file.");
      Emit ("pragma Warnings (Off, ""no entities of * are referenced"");");
      Emit ("pragma Warnings (Off, ""unit * is not referenced"");");
      Emit ("with Prunt.Gcode_Arguments;");
      Emit ("with VSS.Characters.Latin;");
      Emit ("pragma Warnings (On, ""unit * is not referenced"");");
      Emit ("pragma Warnings (On, ""no entities of * are referenced"");");
      Emit ("separate (" & Data.Name & ")");
      Emit ("function Gcode_Commands (This : Module) return Prunt.Module_Types.Gcode_Command_Vectors.Vector is");
      Emit ("pragma Unsuppress (All_Checks);");
      Emit ("begin");
      Emit ("return");
      Emit ("[");

      declare
         First_Cmd : Boolean := True;
      begin
         for C in Data.Gcode_Commands.Iterate loop
            declare
               Key : constant Gcode_Key := Gcode_Command_Maps.Key (C);
            begin
               for Info_Idx in Gcode_Command_Maps.Element (C).First_Index .. Gcode_Command_Maps.Element (C).Last_Index
               loop
                  declare
                     Info : constant Gcode_Command_Data := Gcode_Command_Maps.Element (C) (Info_Idx);
                  begin
                     if not First_Cmd then
                        Emit (",");
                     end if;
                     Emit
                       ("(Identifier  => ('"
                        & Key.Letter
                        & "', "
                        & Conversions.To_Virtual_String (Trim (Key.Number'Image, Both))
                        & "),");
                     Emit (" Name        => """ & Info.Name & """,");
                     Emit (" Description => """ & Info.Description & """,");
                     Emit (" Arguments   =>");

                     if Info.Arguments.Is_Empty then
                        Emit ("[])");
                     else
                        Emit ("[");
                        declare
                           First_Arg : Boolean := True;
                        begin
                           for Arg_C in Info.Arguments.Iterate loop
                              declare
                                 Arg_Name : constant Virtual_String := Gcode_Argument_Maps.Key (Arg_C);
                                 Arg_Data : constant Gcode_Argument_Data := Gcode_Argument_Maps.Element (Arg_C);
                                 Kinds    : Virtual_String;

                                 procedure Add_K (K : Virtual_String) is
                                 begin
                                    if Kinds /= "" then
                                       Kinds.Append (", ");
                                    end if;
                                    Kinds.Append (K & " => True");
                                 end Add_K;
                              begin
                                 if Arg_Name /= "This" and then Arg_Name /= "Planner" then
                                    if not First_Arg then
                                       Emit (",");
                                    end if;

                                    for Kind in Config_Types.Gcode_Argument_Kind loop
                                       if Arg_Data.Arg_Kinds (Kind) then
                                          case Kind is
                                             when Config_Types.Integer_Kind     =>
                                                Add_K ("Gcode_Arguments.Integer_Kind");

                                             when Config_Types.Float_Kind       =>
                                                Add_K ("Gcode_Arguments.Float_Kind");

                                             when Config_Types.String_Kind      =>
                                                Add_K ("Gcode_Arguments.String_Kind");

                                             when Config_Types.No_Value_Kind    =>
                                                Add_K ("Gcode_Arguments.No_Value_Kind");

                                             when Config_Types.Not_Present_Kind =>
                                                Add_K ("Gcode_Arguments.Non_Existent_Kind");
                                          end case;
                                       end if;
                                    end loop;

                                    if Kinds /= "" then
                                       Kinds.Append (", ");
                                    end if;
                                    Kinds.Append ("others => False");

                                    Emit
                                      ("'"
                                       & Arg_Name
                                       & "' => (Allowed_Kinds => ["
                                       & Kinds
                                       & "], Description => """
                                       & Arg_Data.Description
                                       & """)");
                                    First_Arg := False;
                                 end if;
                              end;
                           end loop;
                        end;
                        Emit ("])");
                     end if;

                     First_Cmd := False;
                  end;
               end loop;
            end;
         end loop;
      end;

      Emit ("];");
      Emit ("end Gcode_Commands;");

      Write_File
        (Ada.Directories.Compose
           (Containing_Directory => Out_Dir, Name => Ada.Directories.Base_Name (Filename) & "-gcode_commands.adb"),
         Current_Map_Out);
   end Generate_Gcode_Commands_List;

   procedure Generate_Files (Filename : String; Data : Module_Data; Global_Config : Config_Maps.Map) is
      Config_Map_Out, Reader_Out, Setter_Out : Virtual_String := "";

      Index_Level : Natural := 0;

      function Expand_Index_Level (Expression : Virtual_String) return Virtual_String is
         Expression_Split : constant VSS.String_Vectors.Virtual_String_Vector := Expression.Split ('?');
      begin
         if Expression = "" then
            return "";
         elsif Expression_Split.Length = 1 then
            return Expression_Split.First_Element;
         elsif Expression_Split.Length = 2 then
            if Index_Level = 0 then
               raise Constraint_Error with "Index_? may only be used within an array context.";
            end if;

            return
              Expression_Split.First_Element
              & Conversions.To_Virtual_String (Trim (Integer'Image (Index_Level - 1), Both))
              & Expression_Split.Last_Element;
         else
            raise Constraint_Error with "Only one ? placeholder is supported per expression.";
         end if;
      end Expand_Index_Level;

      procedure Emit_Config_Map (Text : Virtual_String; Location : String := GNAT.Source_Info.Source_Location) is
      begin
         Config_Map_Out.Append (Text);
         Config_Map_Out.Append (" --  " & Conversions.To_Virtual_String (Location));
         Config_Map_Out.Append (VSS.Characters.Latin.Line_Feed);
      end Emit_Config_Map;

      procedure Emit_Reader (Text : Virtual_String; Location : String := GNAT.Source_Info.Source_Location) is
      begin
         Reader_Out.Append (Text);
         Reader_Out.Append (" --  " & Conversions.To_Virtual_String (Location));
         Reader_Out.Append (VSS.Characters.Latin.Line_Feed);
      end Emit_Reader;

      procedure Emit_Setter (Text : Virtual_String; Location : String := GNAT.Source_Info.Source_Location) is
      begin
         Setter_Out.Append (Text);
         Setter_Out.Append (" --  " & Conversions.To_Virtual_String (Location));
         Setter_Out.Append (VSS.Characters.Latin.Line_Feed);
      end Emit_Setter;

      function Path_To_Vector_Access_String (Path : String_Vectors.Vector) return Virtual_String is
         Result : Virtual_String := "";
      begin
         for I in Path.First_Index .. Path.Last_Index loop
            if I > Path.First_Index then
               Result := Result & ", ";
            end if;
            Result := Result & """" & Path (I) & """";
         end loop;

         return Result;
      end Path_To_Vector_Access_String;

      function Effective_Schema_Default (Outer : Component_Data; Fallback : Virtual_String) return Virtual_String is
      begin
         if Outer.Schema_Default_Expr /= "" then
            return Outer.Schema_Default_Expr;
         else
            return Fallback;
         end if;
      end Effective_Schema_Default;

      function Effective_Display_Unit (Inner, Outer : Unit_Data) return Virtual_String is
      begin
         if Inner.Display /= "" then
            return Inner.Display;
         else
            return Outer.Display;
         end if;
      end Effective_Display_Unit;

      function Enum_Literal_Test
        (Enum_Type_Name : Virtual_String; Iterator_Name : Virtual_String; Literal_Name : Virtual_String)
         return Virtual_String
      is
      begin
         return
           Iterator_Name
           & " = "
           & Enum_Type_Name
           & "'Value ("""
           & Literal_Name
           & """)";
      end Enum_Literal_Test;

      function Enum_Literal_Present_When
        (Enum_Val       : Enum_Data;
         Enum_Type_Name : Virtual_String;
         Iterator_Name  : Virtual_String) return Virtual_String
      is
         Result   : Virtual_String := "";
         Is_First : Boolean        := True;
      begin
         if Enum_Val.Present_When.Is_Empty then
            return "True";
         end if;

         Result.Append ("(if ");
         for Cond in Enum_Val.Present_When.Iterate loop
            if not Is_First then
               Result.Append (" elsif ");
            end if;

            Result.Append
              (Enum_Literal_Test (Enum_Type_Name, Iterator_Name, Virtual_String_Maps.Key (Cond))
               & " then "
               & Virtual_String_Maps.Element (Cond));
            Is_First := False;
         end loop;
         Result.Append (" else True)");
         return Result;
      end Enum_Literal_Present_When;

      function Variant_Case_Present_When
        (Record_Val : Record_Data; Variant_Name : Virtual_String) return Virtual_String
      is
      begin
         if Global_Config.Contains (Record_Val.Discriminant_Type)
           and then Global_Config (Record_Val.Discriminant_Type).Kind = Enum_Kind
           and then
             Global_Config (Record_Val.Discriminant_Type).Enum_Value.Present_When.Contains (Variant_Name)
         then
            return Global_Config (Record_Val.Discriminant_Type).Enum_Value.Present_When (Variant_Name);
         else
            return "";
         end if;
      end Variant_Case_Present_When;

      procedure Handle_Item
        (Item          : Config_Type;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Prefix    : Virtual_String);

      procedure Handle_Boolean
        (Boolean_Val   : Boolean_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Expr      : Virtual_String)
      is
         pragma Unreferenced (Boolean_Val);
         Path_Str : constant Virtual_String := Path_To_Vector_Access_String (Path);
      begin
         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_Boolean'(Description => """
            & Outer.Description
            & """, Default => "
            & Effective_Schema_Default (Outer, Outer.Default)
            & ")");
         Emit_Reader
           (Reader_Prefix
            & " := Boolean'(Data.Get(Prunt.Config.Config_Data_Paths.Vector'["
            & Path_Str
            & "]));");
         Emit_Setter ("Data.Set (Prunt.Config.Config_Data_Paths.Vector'[" & Path_Str & "], " & Ada_Expr & ");");
      end Handle_Boolean;

      procedure Handle_Float
        (Float_Val     : Float_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Expr      : Virtual_String)
      is
         Path_Str : constant Virtual_String := Path_To_Vector_Access_String (Path);
      begin
         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_Float'(Description => """
            & Outer.Description
            & """, Default => ("
            & Effective_Schema_Default (Outer, Outer.Default)
            & ")"
            & Virtual_String'
                (if Float_Val.Unit.Conversion /= "" then " / (" & Float_Val.Unit.Conversion & ")" else "")
            & ", Min => ("
            & Outer.Min
            & ")"
            & Virtual_String'
                (if Float_Val.Unit.Conversion /= "" then " / (" & Float_Val.Unit.Conversion & ")" else "")
            & ", Max => ("
            & Outer.Max
            & ")"
            & Virtual_String'
                (if Float_Val.Unit.Conversion /= "" then " / (" & Float_Val.Unit.Conversion & ")" else "")
            & ", Unit => """
            & Effective_Display_Unit (Float_Val.Unit, Outer.Unit)
            & """)");
         Emit_Reader
           (Reader_Prefix
            & " := Data.Get(Prunt.Config.Config_Data_Paths.Vector'["
            & Path_Str
            & "])"
            & (if Float_Val.Unit.Conversion /= "" then " * (" & Float_Val.Unit.Conversion & ")" else "")
            & ";");
         Emit_Setter
           ("Data.Set (Prunt.Config.Config_Data_Paths.Vector'["
            & Path_Str
            & "], ("
            & Ada_Expr
            & ")"
            & (if Float_Val.Unit.Conversion /= "" then " / (" & Float_Val.Unit.Conversion & ")" else "")
            & ");");
      end Handle_Float;

      procedure Handle_Ratio
        (Ratio_Val     : Ratio_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Expr      : Virtual_String)
      is
         pragma Unreferenced (Ratio_Val);
         Path_Str : constant Virtual_String := Path_To_Vector_Access_String (Path);
      begin
         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_Float_Ratio'(Description => """
            & Outer.Description
            & """, Default => "
            & Effective_Schema_Default (Outer, Outer.Default)
            & ", Min => "
            & Outer.Min
            & ", Max => "
            & Outer.Max
            & ")");
         Emit_Reader (Reader_Prefix & " := Data.Get (Prunt.Config.Config_Data_Paths.Vector'[" & Path_Str & "]);");
         Emit_Setter ("Data.Set (Prunt.Config.Config_Data_Paths.Vector'[" & Path_Str & "], " & Ada_Expr & ");");
      end Handle_Ratio;

      procedure Handle_Integer
        (Integer_Val   : Integer_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Expr      : Virtual_String)
      is
         Path_Str : constant Virtual_String := Path_To_Vector_Access_String (Path);
      begin
         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_Integer'(Description => """
            & Outer.Description
            & """, Default => "
            & Effective_Schema_Default (Outer, Outer.Default)
            & Virtual_String'(if Integer_Val.Unit.Conversion /= "" then " / " else "")
            & Integer_Val.Unit.Conversion
            & ", Min => "
            & Outer.Min
            & (if Integer_Val.Unit.Conversion = "" then "" else " / " & Integer_Val.Unit.Conversion)
            & ", Max => "
            & Outer.Max
            & (if Integer_Val.Unit.Conversion = "" then "" else " / " & Integer_Val.Unit.Conversion)
            & ", Unit => """
            & Effective_Display_Unit (Integer_Val.Unit, Outer.Unit)
            & """)");
         Emit_Reader
           (Reader_Prefix
            & " := "
            & Outer.Type_Name
            & "(Long_Long_Integer'(Data.Get (Prunt.Config.Config_Data_Paths.Vector'["
            & Path_Str
            & "])));");
         Emit_Setter
           ("Data.Set (Prunt.Config.Config_Data_Paths.Vector'["
            & Path_Str
            & "], Long_Long_Integer ("
            & Ada_Expr
            & (if Integer_Val.Unit.Conversion /= "" then " / " & Integer_Val.Unit.Conversion else "")
            & "));");
      end Handle_Integer;

      procedure Handle_Component
        (Field         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Expr      : Virtual_String) is
         Present_When : constant Virtual_String := Expand_Index_Level (Field.Present_When);
      begin
         if not Global_Config.Contains (Field.Type_Name) then
            raise Constraint_Error with "Unknown type: " & Field.Type_Name'Image;
         end if;

         if Present_When /= "" then
            Emit_Reader ("if " & Present_When & " then");
            Emit_Setter ("if " & Present_When & " then");
         end if;

         Handle_Item (Global_Config (Field.Type_Name), Field, Path, Reader_Prefix, Ada_Expr);

         if Present_When /= "" then
            Emit_Reader ("end if;");
            Emit_Setter ("end if;");
         end if;
      end Handle_Component;

      procedure Handle_Enum
        (Enum_Val      : Enum_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Expr      : Virtual_String)
      is
         Path_Str : constant Virtual_String := Path_To_Vector_Access_String (Path);
         Options  : constant Virtual_String :=
           (if Outer.Options_Expr /= ""
            then Outer.Options_Expr
            else
              "[for I in "
              & Outer.Type_Name
              & " when "
              & Enum_Literal_Present_When (Enum_Val, Outer.Type_Name, "I")
              & " => +I'Image]");
      begin
         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_Discrete'(Description => """
            & Outer.Description
            & """, Default => "
            & Effective_Schema_Default (Outer, "+" & Outer.Default & "'Image")
            & ", Options => "
            & Options
            & ")");
         Emit_Reader
           (Reader_Prefix
            & " := "
            & Outer.Type_Name
            & "'Value (VSS.Strings.Conversions.To_UTF_8_String (Data.Get (Prunt.Config.Config_Data_Paths.Vector'["
            & Path_Str
            & "])));");
         Emit_Setter
           ("Data.Set (Prunt.Config.Config_Data_Paths.Vector'[" & Path_Str & "], +(" & Ada_Expr & "'Image));");
      end Handle_Enum;

      procedure Handle_Array
        (Array_Val     : Array_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Prefix    : Virtual_String)
      is
         Loop_Index : constant Virtual_String :=
           "Index_" & Conversions.To_Virtual_String (Trim (Index_Level'Image, Both));
      begin
         Index_Level := @ + 1;

         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_Sequence'(Description => """
            & Outer.Description
            & """, Tabbed => "
            & Virtual_String'(if Array_Val.Tabbed then "True" else "False")
            & ", Children => [for "
            & Loop_Index
            & " in "
            & Array_Val.Index_Type
            & " use +"
            & Loop_Index
            & "'Image => ");

         Emit_Reader ("for " & Loop_Index & " in " & Array_Val.Index_Type & " loop");
         Emit_Setter ("for " & Loop_Index & " in " & Array_Val.Index_Type & " loop");

         Handle_Component
           ((Outer
             with delta
               Type_Name   => Array_Val.Element_Type,
               Description => "",
               --  Avoid duplicated description with nested arrays.
               Default     => Outer.Type_Name & "'" & Outer.Default & "(" & Loop_Index & ")",
               Min         => Array_Val.Min,
               Max         => Array_Val.Max),
            Path & [""" & (+" & Loop_Index & "'Image) & """],
            Reader_Prefix & " (" & Loop_Index & ")",
            Ada_Prefix & " (" & Loop_Index & ")");

         Emit_Setter ("end loop;");
         Emit_Reader ("end loop;");
         Emit_Config_Map ("])");

         Index_Level := @ - 1;
      end Handle_Array;

      procedure Handle_Record
        (Record_Val    : Record_Data;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Prefix    : Virtual_String)
      is
         Fixed_Kind_Str    : Virtual_String;
         Fixed_Desc_Suffix : Virtual_String := "";

         function Has_Conditional_Components (Components : Component_Data_Maps.Map) return Boolean is
         begin
            for C in Components.Iterate loop
               if Component_Data_Maps.Element (C).Present_When /= "" then
                  return True;
               end if;
            end loop;

            return False;
         end Has_Conditional_Components;

         function Has_Conditional_Variant_Cases return Boolean is
         begin
            if not Record_Val.Has_Variant then
               return False;
            end if;

            for Variant_C in Record_Val.Variants.Iterate loop
               if Variant_Case_Present_When (Record_Val, Variant_Case_Maps.Key (Variant_C)) /= "" then
                  return True;
               end if;
            end loop;

            return False;
         end Has_Conditional_Variant_Cases;

         procedure Emit_Component_Map
           (Components     : Component_Data_Maps.Map;
            Base_Path      : String_Vectors.Vector;
            Reader_Base    : Virtual_String;
            Ada_Base       : Virtual_String)
         is
            Is_First : Boolean := True;
         begin
            if Components.Is_Empty then
               Emit_Config_Map ("[]");
               return;
            end if;

            if not Has_Conditional_Components (Components) then
               Emit_Config_Map ("[");

               for C in Components.Iterate loop
                  declare
                     Name  : constant Virtual_String := Component_Data_Maps.Key (C);
                     Field : constant Component_Data := Component_Data_Maps.Element (C);
                  begin
                     if not Is_First then
                        Emit_Config_Map (", ");
                     end if;

                     Emit_Config_Map ("""" & Name & """ =>");
                     Handle_Component (Field, Base_Path & [Name], Reader_Base & "." & Name, Ada_Base & "." & Name);
                     Is_First := False;
                  end;
               end loop;

               Emit_Config_Map ("]");
            else
               for C in Components.Iterate loop
                  declare
                     Name  : constant Virtual_String := Component_Data_Maps.Key (C);
                     Field : constant Component_Data := Component_Data_Maps.Element (C);
                     Present_When : constant Virtual_String := Expand_Index_Level (Field.Present_When);
                  begin
                     if not Is_First then
                        Emit_Config_Map (" & ");
                     end if;

                     if Present_When /= "" then
                        Emit_Config_Map ("(if " & Present_When & " then ");
                     end if;

                     Emit_Config_Map ("[""" & Name & """ =>");
                     Handle_Component (Field, Base_Path & [Name], Reader_Base & "." & Name, Ada_Base & "." & Name);
                     Emit_Config_Map ("]");

                     if Present_When /= "" then
                        Emit_Config_Map (" else [])");
                     end if;

                     Is_First := False;
                  end;
               end loop;
            end if;
         end Emit_Component_Map;
      begin
         if Outer.Fixed_Kind /= "" then
            Fixed_Kind_Str := Expand_Index_Level (Outer.Fixed_Kind);

            if Record_Val.Has_Variant then
               declare
                  Is_First : Boolean := True;
               begin
                  Fixed_Desc_Suffix.Append (" & (if ");
                  for Variant_C in Record_Val.Variants.Iterate loop
                     if not Is_First then
                        Fixed_Desc_Suffix.Append (" elsif ");
                     end if;
                     Fixed_Desc_Suffix.Append (Fixed_Kind_Str & " = " & Variant_Case_Maps.Key (Variant_C));
                     Fixed_Desc_Suffix.Append
                       (" then +""\n" & Variant_Case_Maps.Element (Variant_C).Description & """");
                     Is_First := False;
                  end loop;

                  if not Is_First then
                     Fixed_Desc_Suffix.Append (" else +"""")");
                  else
                     Fixed_Desc_Suffix := "";
                  end if;
               end;
            end if;
         end if;

         Emit_Config_Map
           ("Prunt.Config.Config_Property_Parameters_Sequence'(Tabbed => "
            & Virtual_String'(if Record_Val.Tabbed then "True" else "False")
            & ", Description => """
            & Record_Val.Description
            & """"
            & Fixed_Desc_Suffix
            & ", Children => Prunt.Config.Config_Property_Maps.""&"" (");
         --  Call `&` as a regular function so we can swap the arguments and place the variant part after the
         --  non-variant part. We can not simply place the variant code after the non-variant code generation as we use
         --  a delta aggregate to set the non-variant fields and delta aggregates can not set discriminants, which the
         --  variant code does.

         if Outer.Fixed_Kind /= "" then
            declare
               Is_First : Boolean := True;
            begin
               Emit_Config_Map ("Right => (");

               for Variant_C in Record_Val.Variants.Iterate loop
                  Emit_Config_Map
                    (Virtual_String'(if Is_First then "" else "els")
                     & "if "
                     & Fixed_Kind_Str
                     & " = "
                     & Variant_Case_Maps.Key (Variant_C)
                     & " then ");
                  Emit_Reader
                    (Virtual_String'(if Is_First then "" else "els")
                     & "if "
                     & Fixed_Kind_Str
                     & " = "
                     & Variant_Case_Maps.Key (Variant_C)
                     & " then");
                  Emit_Reader
                    (Reader_Prefix
                     & " := ("
                     & Record_Val.Discriminant
                     & " => "
                     & Variant_Case_Maps.Key (Variant_C)
                     & ", others => <>);");
                  Emit_Setter
                    (Virtual_String'(if Is_First then "" else "els")
                     & "if "
                     & Ada_Prefix
                     & "."
                     & Record_Val.Discriminant
                     & " = "
                     & Variant_Case_Maps.Key (Variant_C)
                     & " then");

                  Emit_Setter ("null;");

                  Emit_Component_Map
                    (Variant_Case_Maps.Element (Variant_C).Components,
                     Path,
                     Reader_Prefix,
                     Ada_Prefix);

                  Is_First := False;
               end loop;

               Emit_Reader ("else");
               Emit_Reader ("raise Constraint_Error;");
               Emit_Reader ("end if;");
               Emit_Config_Map ("else raise Constraint_Error),");
               Emit_Setter ("else");
               Emit_Setter ("raise Constraint_Error;");
               Emit_Setter ("end if;");
            end;
         elsif Record_Val.Has_Variant then
            declare
               Is_First : Boolean := True;
            begin
               Emit_Config_Map
                 ("Right => ["""
                  & Record_Val.Discriminant
                  & """ => Prunt.Config.Config_Property_Parameters_Variant'(Default => """
                  & Record_Val.Discriminant_Default
                  & """, Description => """", Children => ");
               --  Call `&` as a regular function so we can swap the arguments and place the variant part after the
               --  non-variant part. We can not simply place this code after the non-variant code generation as we use
               --  a delta aggregate to set the non-variant fields and delta aggregates can not set discriminants,
               --  which this code does.

               if not Has_Conditional_Variant_Cases then
                  Emit_Config_Map ("[");

                  for Variant_C in Record_Val.Variants.Iterate loop
                     declare
                        Name : constant Virtual_String := Variant_Case_Maps.Key (Variant_C);
                     begin
                        if not Is_First then
                           Emit_Config_Map (", ");
                        end if;

                        Emit_Config_Map
                          (""""
                           & Name
                           & """ => Prunt.Config.Config_Property_Parameters_Sequence'(Tabbed => "
                           & Virtual_String'(if Record_Val.Tabbed then "True" else "False")
                           & ", Description => """
                           & Variant_Case_Maps.Element (Variant_C).Description
                           & """, Children => ");
                        Emit_Reader
                          (Virtual_String'(if Is_First then "" else "els")
                           & "if Data.Get (Prunt.Config.Config_Data_Paths.Vector'["
                           & Path_To_Vector_Access_String (Path & [Record_Val.Discriminant, "Selected"])
                           & "]) = """
                           & Name
                           & """ then "
                           & Reader_Prefix
                           & " := ("
                           & Record_Val.Discriminant
                           & " => "
                           & Name
                           & ", others => <>);");
                        Emit_Setter
                          (Virtual_String'(if Is_First then "" else "els")
                           & "if "
                           & Ada_Prefix
                           & "."
                           & Record_Val.Discriminant
                           & " = "
                           & Name
                           & " then");

                        Emit_Setter ("null;");

                        Emit_Component_Map
                          (Variant_Case_Maps.Element (Variant_C).Components,
                           Path & [Record_Val.Discriminant, "Children", Name],
                           Reader_Prefix,
                           Ada_Prefix);

                        Emit_Config_Map (")");
                        Is_First := False;
                     end;
                  end loop;

                  Emit_Config_Map ("]");
               else
                  for Variant_C in Record_Val.Variants.Iterate loop
                     declare
                        Name      : constant Virtual_String := Variant_Case_Maps.Key (Variant_C);
                        Condition : constant Virtual_String := Variant_Case_Present_When (Record_Val, Name);
                     begin
                        Emit_Config_Map (Virtual_String'(if Is_First then "" else " & "));
                        if Condition /= "" then
                           Emit_Config_Map ("(if " & Condition & " then ");
                        end if;

                        Emit_Config_Map
                          ("["""
                           & Name
                           & """ => Prunt.Config.Config_Property_Parameters_Sequence'(Tabbed => "
                           & Virtual_String'(if Record_Val.Tabbed then "True" else "False")
                           & ", Description => """
                           & Variant_Case_Maps.Element (Variant_C).Description
                           & """, Children => ");
                        Emit_Reader
                          (Virtual_String'(if Is_First then "" else "els")
                           & "if Data.Get (Prunt.Config.Config_Data_Paths.Vector'["
                           & Path_To_Vector_Access_String (Path & [Record_Val.Discriminant, "Selected"])
                           & "]) = """
                           & Name
                           & """ then "
                           & Reader_Prefix
                           & " := ("
                           & Record_Val.Discriminant
                           & " => "
                           & Name
                           & ", others => <>);");
                        Emit_Setter
                          (Virtual_String'(if Is_First then "" else "els")
                           & "if "
                           & Ada_Prefix
                           & "."
                           & Record_Val.Discriminant
                           & " = "
                           & Name
                           & " then");

                        Emit_Setter ("null;");

                        Emit_Component_Map
                          (Variant_Case_Maps.Element (Variant_C).Components,
                           Path & [Record_Val.Discriminant, "Children", Name],
                           Reader_Prefix,
                           Ada_Prefix);

                        Emit_Config_Map (")]");
                        if Condition /= "" then
                           Emit_Config_Map (" else [])");
                        end if;

                        Is_First := False;
                     end;
                  end loop;
               end if;

               Emit_Reader ("else");
               Emit_Reader ("raise Constraint_Error;");
               Emit_Reader ("end if;");
               Emit_Config_Map (")],");
               Emit_Setter ("else");
               Emit_Setter ("raise Constraint_Error;");
               Emit_Setter ("end if;");
            end;
         else
            Emit_Config_Map ("Right => [],");
         end if;

         if Record_Val.Components.Is_Empty and then not Record_Val.Has_Variant then
            Emit_Setter ("null;");
         end if;

         Emit_Config_Map ("Left => ");
         Emit_Component_Map (Record_Val.Components, Path, Reader_Prefix, Ada_Prefix);
         Emit_Config_Map ("))");
      end Handle_Record;

      procedure Handle_Item
        (Item          : Config_Type;
         Outer         : Component_Data;
         Path          : String_Vectors.Vector;
         Reader_Prefix : Virtual_String;
         Ada_Prefix    : Virtual_String) is
      begin
         case Item.Kind is
            when Record_Kind  =>
               Handle_Record (Item.Record_Value, Outer, Path, Reader_Prefix, Ada_Prefix);

            when Array_Kind   =>
               Handle_Array (Item.Array_Value, Outer, Path, Reader_Prefix, Ada_Prefix);

            when Enum_Kind    =>
               Handle_Enum (Item.Enum_Value, Outer, Path, Reader_Prefix, Ada_Prefix);

            when Boolean_Kind =>
               Handle_Boolean (Item.Boolean_Value, Outer, Path, Reader_Prefix, Ada_Prefix);

            when Integer_Kind =>
               Handle_Integer (Item.Integer_Value, Outer, Path, Reader_Prefix, Ada_Prefix);

            when Float_Kind   =>
               Handle_Float (Item.Float_Value, Outer, Path, Reader_Prefix, Ada_Prefix);

            when Ratio_Kind   =>
               Handle_Ratio (Item.Ratio_Value, Outer, Path, Reader_Prefix, Ada_Prefix);
         end case;
      end Handle_Item;
   begin

      if not Ada.Directories.Exists (Out_Dir) then
         Ada.Directories.Create_Directory (Out_Dir);
      end if;

      if Data.Root_Type /= "" and then Data.Config.Contains (Data.Root_Type) then
         Emit_Config_Map ("pragma Style_Checks (Off);");
         Emit_Config_Map
           ("--  This file is automatically generated based on the contents of "
            & Conversions.To_Virtual_String (Filename));
         Emit_Config_Map ("--  Run config_codegen to regenerate this file.");
         Emit_Config_Map ("pragma Warnings (Off, ""no entities of * are referenced"");");
         Emit_Config_Map ("pragma Warnings (Off, ""unit * is not referenced"");");
         Emit_Config_Map ("with VSS.Characters.Latin;");
         Emit_Config_Map ("with Prunt.Config;");
         Emit_Config_Map ("pragma Warnings (On, ""unit * is not referenced"");");
         Emit_Config_Map ("pragma Warnings (On, ""no entities of * are referenced"");");
         Emit_Config_Map ("separate (" & Data.Name & ")");
         Emit_Config_Map ("function Build_Schema return Prunt.Config.Config_Property_Maps.Map is");
         Emit_Config_Map ("pragma Unsuppress (All_Checks);");
         Emit_Config_Map ("pragma Warnings (Off, ""use clause for private type * has no effect"");");
         Emit_Config_Map ("pragma Warnings (Off, ""use clause for type * has no effect"");");
         Emit_Config_Map ("use type Prunt.Config.Config_Property_Maps.Map;");
         Emit_Config_Map ("pragma Warnings (On, ""use clause for type * has no effect"");");
         Emit_Config_Map ("pragma Warnings (On, ""use clause for private type * has no effect"");");
         Emit_Config_Map ("begin");
         Emit_Config_Map ("pragma Extensions_Allowed (On);");
         Emit_Config_Map ("return");

         Emit_Reader ("pragma Style_Checks (Off);");
         Emit_Reader
           ("--  This file is automatically generated based on the contents of "
            & Conversions.To_Virtual_String (Filename));
         Emit_Reader ("--  Run config_codegen to regenerate this file.");
         Emit_Reader ("pragma Warnings (Off, ""no entities of * are referenced"");");
         Emit_Reader ("pragma Warnings (Off, ""unit * is not referenced"");");
         Emit_Reader ("with VSS.Characters.Latin;");
         Emit_Reader ("pragma Warnings (On, ""unit * is not referenced"");");
         Emit_Reader ("pragma Warnings (On, ""no entities of * are referenced"");");
         Emit_Reader ("separate (" & Data.Name & ")");
         Emit_Reader
           ("function Config_Data_To_User_Config (Data : Prunt.Config.Config_Data) return User_Config is");
         Emit_Reader ("pragma Unsuppress (All_Checks);");
         Emit_Reader ("begin");
         Emit_Reader ("pragma Extensions_Allowed (On);");
         Emit_Reader ("return Result : User_Config do");

         Emit_Setter ("pragma Style_Checks (Off);");
         Emit_Setter
           ("--  This file is automatically generated based on the contents of "
            & Conversions.To_Virtual_String (Filename));
         Emit_Setter ("--  Run config_codegen to regenerate this file.");
         Emit_Setter ("pragma Warnings (Off, ""no entities of * are referenced"");");
         Emit_Setter ("pragma Warnings (Off, ""unit * is not referenced"");");
         Emit_Setter ("with VSS.Characters.Latin;");
         Emit_Setter ("pragma Warnings (On, ""unit * is not referenced"");");
         Emit_Setter ("pragma Warnings (On, ""no entities of * are referenced"");");
         Emit_Setter ("separate (" & Data.Name & ")");
         Emit_Setter
           ("procedure User_Config_To_Config_Data (Data : in out Prunt.Config.Config_Data; Config : User_Config) is");
         Emit_Setter ("pragma Unsuppress (All_Checks);");
         Emit_Setter ("pragma Extensions_Allowed (On);");
         Emit_Setter ("begin");

         Handle_Item
           (Item          => Data.Config (Data.Root_Type),
            Outer         => (others => <>),
            Path          => [],
            Reader_Prefix => "Result",
            Ada_Prefix    => "Config");

         Emit_Setter ("end User_Config_To_Config_Data;");

         Emit_Reader ("end return;");
         Emit_Reader ("end Config_Data_To_User_Config;");

         Emit_Config_Map (".Children;");
         Emit_Config_Map ("end Build_Schema;");


         Write_File
           (Ada.Directories.Compose
              (Containing_Directory => Out_Dir, Name => Ada.Directories.Base_Name (Filename) & "-build_schema.adb"),
            Config_Map_Out);
         Write_File
           (Ada.Directories.Compose
              (Containing_Directory => Out_Dir,
               Name                 => Ada.Directories.Base_Name (Filename) & "-config_data_to_user_config.adb"),
            Reader_Out);
         Write_File
           (Ada.Directories.Compose
              (Containing_Directory => Out_Dir,
               Name                 => Ada.Directories.Base_Name (Filename) & "-user_config_to_config_data.adb"),
            Setter_Out);
      end if;

      if not Data.Gcode_Commands.Is_Empty then
         Generate_Gcode_Dispatch (Filename, Data);
         Generate_Gcode_Commands_List (Filename, Data);
      end if;
   end Generate_Files;

end Config_Generator;
