name = "config_codegen"
description = ""
version = "0.1.0-dev"

authors = ["Liam Powell"]
maintainers = ["Liam Powell <liam@liampll.com>"]
maintainers-logins = ["liampwll"]
licenses = "MIT"
website = ""
tags = []

executables = ["config_codegen", "package_subprogram_audit"]

[[depends-on]]
gnat_native = "~16.2.1002"
# From here: https://github.com/Prunt3D/prunt_alire_index

[[depends-on]]
libadalang_prebuilt = "^26.0.1003"

[build-switches]
"*".style_checks = "No"

[[pins]]
gnat_native = "16.2.1002"
gnat = "16.2.1002"
libadalang_prebuilt = "26.0.1003"
